(function(g){var window=this;var j4=function(a,b,c){var d=b.sa();g.I(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.zc(c?c:"mqdefault.jpg");var f=b instanceof g.oB&&b.lengthSeconds?g.bR(b.lengthSeconds):null,k=!!e;e=k&&"RD"==(new g.kE(e.substr(0,2),e.substr(2))).type;var l=b instanceof g.oB?b.ua:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:b.author,aria_label:b.kj||g.HN("\u89c0\u770b\u300c$TITLE\u300d",{TITLE:b.title}),duration:f,url:b.Wh(),
is_live:l,is_list:k,is_mix:e,background:c?"background-image: url("+c+")":""};b instanceof g.mE&&(d.playlist_length=b.getLength());a.update(d)},k4=function(a,b){g.jD.call(this,{B:"div",
W:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.player=a;this.created=!1},l4=function(a){g.W.call(this,{B:"div",
W:["ytp-upnext","ytp-player-content"],L:{"aria-label":"{{aria_label}}"},J:[{B:"div",G:"ytp-cued-thumbnail-overlay-image",L:{style:"{{background}}"}},{B:"span",G:"ytp-upnext-top",J:[{B:"span",G:"ytp-upnext-header",V:"\u5373\u5c07\u64ad\u653e"},{B:"span",G:"ytp-upnext-title",V:"{{title}}"},{B:"span",G:"ytp-upnext-author",V:"{{author}}"}]},{B:"a",G:"ytp-upnext-autoplay-icon",L:{role:"button",href:"{{url}}","aria-label":"\u64ad\u653e\u4e0b\u4e00\u90e8\u5f71\u7247"},J:[{B:"svg",L:{height:"100%",version:"1.1",
viewBox:"0 0 72 72",width:"100%"},J:[{B:"circle",G:"ytp-svg-autoplay-circle",L:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{B:"circle",G:"ytp-svg-autoplay-ring",L:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{B:"path",G:"ytp-svg-fill",L:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{B:"span",G:"ytp-upnext-bottom",J:[{B:"span",G:"ytp-upnext-cancel"},
{B:"span",G:"ytp-upnext-paused",V:"\u5df2\u66ab\u505c\u81ea\u52d5\u64ad\u653e\u529f\u80fd"}]}]});this.A=null;var b=this.i["ytp-upnext-cancel"];this.A=new g.W({B:"button",W:["ytp-upnext-cancel-button","ytp-button"],L:{tabindex:"0","aria-label":"\u53d6\u6d88\u81ea\u52d5\u64ad\u653e"},V:"\u53d6\u6d88"});g.C(this,this.A);this.A.da("click",this.vI,this);this.A.g(b);this.l=a;this.I=this.i["ytp-svg-autoplay-ring"];this.D=this.C=this.o=this.u=null;this.F=new g.J(this.Yl,5E3,this);g.C(this,this.F);this.H=
0;this.K(this.i["ytp-upnext-autoplay-icon"],"click",this.iK);this.Ny();this.K(a,"autonavvisibility",this.Ny);this.K(a,"mdxnowautoplaying",this.AJ);this.K(a,"mdxautoplaycanceled",this.BJ);this.K(a,"mdxautoplayupnext",this.iB);3==this.l.getPresentingPlayerType()&&(a=(a=g.zK(g.tK(this.l)))?a.pD():null)&&this.iB(a)},m4=function(a,b){if(!a.o){g.gq("a11y-announce","\u5373\u5c07\u64ad\u653e "+a.u.title);
a.H=g.M();a.o=new g.J((0,g.x)(a.np,a,b),25);a.np(b);var c=b||g.P(g.X(a.l).experiments,"autoplay_time")||1E4;a.l.la("onAutonavCoundownStarted",c)}g.io(a.element,"ytp-upnext-autoplay-paused")},o4=function(a){n4(a);
a.H=g.M();a.np();g.H(a.element,"ytp-upnext-autoplay-paused")},n4=function(a){a.o&&(a.o.dispose(),a.o=null)},p4=function(a,b){b=void 0===b?!1:b;
if(g.O(g.X(a.l).experiments,"autonav_notifications")&&b&&window.Notification&&document.hasFocus){var c=Notification.permission;"default"==c?Notification.requestPermission():"granted"!=c||document.hasFocus()||(c=a.u.sa(),a.Yl(),a.C=new Notification("\u5373\u5c07\u64ad\u653e",{body:c.title,icon:c.zc()}),a.D=a.K(a.C,"click",a.aK),a.F.start())}n4(a);a.l.nextVideo(!1,b)},q4=function(a){k4.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.l=new g.W({B:"div",G:"ytp-subscribe-card",J:[{B:"img",G:"ytp-author-image",L:{src:b.Wd}},{B:"div",G:"ytp-subscribe-card-right",J:[{B:"div",G:"ytp-author-name",V:b.author},{B:"div",G:"html5-subscribe-button-container"}]}]});g.C(this,this.l);this.l.g(this.element);this.o=new g.nW("\u8a02\u95b1",null,"\u53d6\u6d88\u8a02\u95b1",null,!0,!1,b.Sf,b.subscribed,"trailer-endscreen",null,null,a);g.C(this,this.o);this.o.g(this.l.i["html5-subscribe-button-container"]);this.hide()},
r4=function(a){var b=g.X(a),c=g.gx||g.Ch?{style:"will-change: opacity"}:void 0,d=b.i,e=["ytp-videowall-still"];
b.g&&e.push("ytp-videowall-show-text");g.W.call(this,{B:"a",W:e,L:{href:"{{url}}",target:d?b.A:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},J:[{B:"div",G:"ytp-videowall-still-image",L:{style:"{{background}}"}},{B:"span",G:"ytp-videowall-still-info",J:[{B:"span",G:"ytp-videowall-still-info-bg",J:[{B:"span",G:"ytp-videowall-still-info-content",L:c,J:[{B:"span",G:"ytp-videowall-still-info-title",V:"{{title}}"},{B:"span",G:"ytp-videowall-still-info-author",
V:"{{author_and_views}}"},{B:"span",G:"ytp-videowall-still-info-live",V:"\u76f4\u64ad"},{B:"span",G:"ytp-videowall-still-info-duration",V:"{{duration}}"}]}]}]},{B:"span",W:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],J:[{B:"span",G:"ytp-videowall-still-listlabel-icon"},"\u64ad\u653e\u6e05\u55ae",{B:"span",G:"ytp-videowall-still-listlabel-length",J:[" (",{B:"span",V:"{{playlist_length}}"},")"]}]},{B:"span",W:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],
J:[{B:"span",G:"ytp-videowall-still-listlabel-mix-icon"},"\u5408\u8f2f",{B:"span",G:"ytp-videowall-still-listlabel-length",V:" (50+)"}]}]});this.A=d;this.l=a;this.o=null;this.u=new g.Ls(this);g.C(this,this.u);this.da("click",this.D);this.da("keypress",this.F);this.u.K(a,"videodatachange",this.C);g.X(a).F&&g.vO(a.app.T,this.element,this);this.C()},s4=function(a){g.PK(a.l,a.element);
var b=a.o.sa().videoId,c=a.o.getPlaylistId();g.tY(a.l.app,b,a.o.Eb,c,void 0,void 0)},t4=function(a){k4.call(this,a,"videowall-endscreen");
this.F=a;this.A=0;this.o=[];this.C=this.O=this.u=null;this.D=this.R=!1;this.M=null;this.ca=new g.Ls(this);g.C(this,this.ca);this.H=new g.J(g.Qa(g.H,this.element,"ytp-show-tiles"),0);g.C(this,this.H);var b=new g.W({B:"button",W:["ytp-button","ytp-endscreen-previous"],L:{"aria-label":"\u4e0a\u4e00\u90e8"},J:[g.KP()]});g.C(this,b);b.g(this.element);b.da("click",this.MF,this);this.I=new g.dD({B:"div",G:"ytp-endscreen-content"});g.C(this,this.I);this.I.g(this.element);b=new g.W({B:"button",W:["ytp-button",
"ytp-endscreen-next"],L:{"aria-label":"\u4e0b\u4e00\u500b"},J:[g.LP()]});g.C(this,b);b.g(this.element);b.da("click",this.LF,this);this.l=new l4(a);g.C(this,this.l);g.MK(this.player,this.l.element,4);this.hide()},u4=function(a){return g.NK(a.player)&&a.Ju()&&!a.C},v4=function(a,b){return(0,g.ge)(b.suggestions,function(c){c=g.qS(g.X(a.F),c);
g.C(a,c);return c})},w4=function(a){var b=a.Qe();
b!=a.R&&(a.R=b,a.player.N("autonavvisibility"))},y4=function(a){g.$K.call(this,a);
this.g=null;this.i=new g.Ls(this);g.C(this,this.i);this.l=g.X(a);x4(a)?this.g=new t4(this.player):this.l.Ia?this.g=new q4(this.player):this.g=new k4(this.player);g.C(this,this.g);g.MK(this.player,this.g.element,4);this.gA();this.i.K(a,"videodatachange",this.gA,this);this.i.K(a,g.jE("endscreen"),this.aF,this);this.i.K(a,"crx_endscreen",this.bF,this)},x4=function(a){a=g.X(a);
return a.Ea&&!a.Ia};
g.t(k4,g.jD);k4.prototype.create=function(){this.created=!0};
k4.prototype.destroy=function(){this.created=!1};
k4.prototype.Ju=function(){return!1};
k4.prototype.Qe=function(){return!1};g.t(l4,g.W);g.h=l4.prototype;g.h.Yl=function(){this.C&&(this.F.stop(),this.La(this.D),this.D=null,this.C.close(),this.C=null)};
g.h.Ny=function(){g.iD(this,this.l.Qe())};
g.h.aK=function(){window.focus();this.Yl()};
g.h.hide=function(){g.W.prototype.hide.call(this)};
g.h.np=function(a){a=a||g.P(g.X(this.l).experiments,"autoplay_time")||1E4;var b=Math.min(g.M()-this.H,a);a=Math.min(b/a,1);this.I.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.l.getPresentingPlayerType()?p4(this,!0):this.o&&this.o.start()};
g.h.iK=function(a){!g.$d(this.A.element,g.ds(a))&&g.tS(a,this.l)&&p4(this)};
g.h.vI=function(){g.vK(this.l,!0)};
g.h.AJ=function(a){this.l.getPresentingPlayerType();this.show();m4(this,a)};
g.h.iB=function(a){this.l.getPresentingPlayerType();this.u&&this.u.sa().videoId==a.sa().videoId||(this.u=a,j4(this,a,"hqdefault.jpg"))};
g.h.BJ=function(){this.l.getPresentingPlayerType();n4(this);this.hide()};
g.h.U=function(){n4(this);this.Yl();g.W.prototype.U.call(this)};g.t(q4,k4);g.t(r4,g.W);r4.prototype.D=function(a){g.tS(a,this.l,this.A,this.o.Eb||void 0)&&s4(this)};
r4.prototype.F=function(a){switch(a.keyCode){case 13:case 32:g.is(a)||(s4(this),g.hs(a))}};
r4.prototype.C=function(){var a=this.l.getVideoData(),b=g.X(this.l);this.A=a.Qb?!1:b.i};g.t(t4,k4);g.h=t4.prototype;g.h.create=function(){k4.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.u=v4(this,a),this.O=a);this.Lf();this.ca.K(this.player,"appresize",this.Lf);this.ca.K(this.player,"onVideoAreaChange",this.Lf);this.ca.K(this.player,"videodatachange",this.NF);this.ca.K(this.player,"autonavchange",this.yr);this.ca.K(this.player,"autonavcancel",this.KF);a=this.O.autonavState;a!=this.M&&this.yr(a);this.ca.K(this.element,"transitionend",this.xL)};
g.h.destroy=function(){g.Ns(this.ca);g.rf(this.o);this.o=[];this.u=null;k4.prototype.destroy.call(this);g.io(this.element,"ytp-show-tiles");this.H.stop();this.M=this.O.autonavState};
g.h.Ju=function(){return 1!=this.O.autonavState};
g.h.show=function(){k4.prototype.show.call(this);g.io(this.element,"ytp-show-tiles");g.X(this.player).g?g.wo(this.H):this.H.start();(this.D||this.C&&this.C!=this.O.clientPlaybackNonce)&&g.vK(this.player,!1);u4(this)?(w4(this),2==this.O.autonavState?g.O(g.X(this.player).experiments,"fast_autonav_in_background")&&3==this.player.getVisibilityState()?p4(this.l,!0):m4(this.l):3==this.O.autonavState&&o4(this.l)):(g.vK(this.player,!0),w4(this))};
g.h.hide=function(){k4.prototype.hide.call(this);o4(this.l);w4(this)};
g.h.xL=function(a){g.ds(a)==this.element&&this.Lf()};
g.h.Lf=function(){if(this.u&&this.u.length){g.H(this.element,"ytp-endscreen-paginate");var a=g.DK(this.F,!0),b=g.yD(this.F);b&&(b=b.ec()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.u.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var p=b/2,r=e/2,v=b<=f-2&&n>=r*m,z=e<=k-2&&n>=p*m;if((p+1)/r*d/c>c/(p/(r+1)*d)&&z)n-=p*m,e+=2;else if(v)n-=r*m,b+=2;else if(z)n-=p*m,e+=2;else break}d=
!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.pd(a.width/m||1,1,1.21);n*=g.pd(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.I.element;g.Rh(a,m,n);g.zh(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});c=this.l;f=this.u[0];c.u=f;j4(c,f,"hqdefault.jpg");g.I(this.element,"ytp-endscreen-takeover",u4(this));w4(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(p=c,r=0,d&&f>=b-2&&k>=e-
2?r=1:0==k%2&&0==f%2&&(2>k&&2>f?0==k&&0==f&&(r=2):r=2),p=g.qd(p+this.A,l),0!=r){v=this.o[c];v||(v=new r4(this.player),this.o[c]=v,a.appendChild(v.element));z=Math.floor(n*k/e);var B=Math.floor(m*f/b),F=Math.floor(n*(k+r)/e)-z-4,E=Math.floor(m*(f+r)/b)-B-4;g.Hh(v.element,B,z);g.Rh(v.element,E,F);g.zh(v.element,"transitionDelay",(k+f)/20+"s");g.I(v.element,"ytp-videowall-still-mini",1==r);g.I(v.element,"ytp-videowall-still-large",2<r);r=v;p=this.u[p];r.o!=p&&(r.o=p,j4(r,p,g.go(r.element,"ytp-videowall-still-large")?
"hqdefault.jpg":"mqdefault.jpg"),p=(p=p.Eb)&&p.itct)&&(v=r.l,g.X(v).F&&g.wO(v.app.T,r.element,p));c++}g.I(this.element,"ytp-endscreen-paginate",c<l);for(b=this.o.length-1;b>=c;b--)e=this.o[b],g.Wd(e.element),g.qf(e);this.o.length=c}};
g.h.NF=function(){var a=this.player.getVideoData();this.O!=a&&(this.A=0,this.u=v4(this,a),this.O=a,this.Lf())};
g.h.LF=function(){this.A+=this.o.length;this.Lf()};
g.h.MF=function(){this.A-=this.o.length;this.Lf()};
g.h.pE=function(){return!!this.l.o};
g.h.yr=function(a){1==a?(this.D=!1,this.C=this.O.clientPlaybackNonce,n4(this.l),this.Fa()&&this.Lf()):(this.D=!0,this.Fa()&&u4(this)&&(2==a?m4(this.l):3==a&&o4(this.l)))};
g.h.KF=function(a){if(a){for(a=0;a<this.o.length;a++)g.QK(this.F,this.o[a].element,!0);this.yr(1)}else this.C=null,this.D=!1;this.Lf()};
g.h.Qe=function(){return this.Fa()&&u4(this)};g.t(y4,g.$K);g.h=y4.prototype;g.h.Vk=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!x4(this.player)||b;a=a.Oc||g.Yy(a.Na);var c=g.UX(this.player.app);return b&&!a&&!c};
g.h.Qe=function(){return this.g.Qe()};
g.h.kE=function(){return this.Qe()?this.g.pE():!1};
g.h.U=function(){g.IK(this.player,"endscreen");g.$K.prototype.U.call(this)};
g.h.load=function(){g.$K.prototype.load.call(this);this.g.show()};
g.h.unload=function(){g.$K.prototype.unload.call(this);this.g.hide();this.g.destroy()};
g.h.aF=function(a){this.Vk()&&(this.g.created||this.g.create(),"load"==a.getId()&&this.load())};
g.h.bF=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.gA=function(){g.IK(this.player,"endscreen");var a=this.player.getVideoData();a=new g.gE(Math.max(1E3*(a.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});g.C(this,a);var b=new g.gE(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.C(this,b);g.FK(this.player,[a,b])};g.uV.endscreen=y4;})(_yt_player);
