(function(g){var window=this;var bqa=function(a,b){return g.Ub(a,b)},J5=function(){},cqa=function(a){if(a.Ac&&"function"==typeof a.Ac)return a.Ac();
if(g.Da(a))return a.split("");if(g.La(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Qb(a)},dqa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.La(a)||g.Da(a))(0,g.y)(a,b,void 0);else{if(a.Od&&"function"==typeof a.Od)var c=a.Od();else if(a.Ac&&"function"==typeof a.Ac)c=void 0;else if(g.La(a)||g.Da(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Rb(a);d=cqa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},K5=function(a){g.kn(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.D)()).toString(36));
return a},L5=function(a,b,c){g.Ka(c)||(c=[String(c)]);
g.pn(a.l,b,c)},M5=function(a){return(a=g.Io(a))?new ActiveXObject(a):new XMLHttpRequest},N5=function(a,b){return b+" ["+a.Y+" "+a.D+" "+a.getStatus()+"]"},eqa=function(a){return"content-type"==a.toLowerCase()},O5=function(a){a.g&&a.I&&(a.g.ontimeout=null);
a.F&&(g.u.clearTimeout(a.F),a.F=null)},fqa=function(a){return g.Ld&&g.nd(9)&&g.Fa(a.timeout)&&g.Ca(a.ontimeout)},P5=function(a){a.R||(a.R=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},Q5=function(a,b){if(a.g){O5(a);
var c=a.g,d=a.P[0]?g.Ha:null;a.g=null;a.P=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},R5=function(a,b){a.i=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.l=b;a.u=5;P5(a);Q5(a)},S5=function(a){return a.g?a.g.readyState:0},T5=function(a){if(a.i&&"undefined"!=typeof g.JY)if(a.P[1]&&4==S5(a)&&2==a.getStatus())N5(a,"Local request error detected and ignored");
else if(a.C&&4==S5(a))g.Gg(a.ww,0,a);else if(a.dispatchEvent("readystatechange"),4==S5(a)){N5(a,"Request complete");a.i=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Sg(1,String(a.D));if(!f&&g.u.self&&g.u.self.location){var k=g.u.self.location.protocol;f=k.substr(0,k.length-1)}e=!gqa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.u=6;try{var l=2<S5(a)?a.g.statusText:""}catch(m){l=""}a.l=l+" ["+a.getStatus()+"]";P5(a)}}finally{Q5(a)}}},U5=function(a){g.Sf.call(this);
this.headers=new g.Zm;this.M=a||null;this.i=!1;this.P=this.g=null;this.Y=this.D="";this.u=0;this.l="";this.o=this.aa=this.C=this.R=!1;this.A=0;this.F=null;this.X="";this.I=this.T=!1},V5=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},hqa=function(a,b){var c=[];
g.Ok(b,function(d){try{var e=g.Xo.prototype.i.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.Ca(e)?g.Wo(e)&&c.push(d):c.push(d)},a);
return c},iqa=function(a,b){var c=hqa(a,b);
(0,g.y)(c,function(d){g.Xo.prototype.remove.call(this,d)},a)},W5=function(a){if(a.fd){if(a.fd.locationOverrideToken)return{locationOverrideToken:a.fd.locationOverrideToken};
if(null!=a.fd.latitudeE7&&null!=a.fd.longitudeE7)return{latitudeE7:a.fd.latitudeE7,longitudeE7:a.fd.longitudeE7}}return null},jqa=function(a,b){g.$a(a,b)||a.push(b)},X5=function(a){var b=0,c;
for(c in a)b++;return b},Y5=function(a,b){var c=b instanceof g.xc?b:g.Dc(b,/^data:image\//i.test(b));
a.src=g.yc(c)},kqa=function(a){try{return g.u.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},lqa=function(a,b,c,d){var e=new g.bn(null,void 0);
a&&g.cn(e,a);b&&g.dn(e,b);c&&g.en(e,c);d&&(e.i=d);return e},Z5=function(a){if(g.u.JSON)try{return g.u.JSON.parse(a)}catch(b){}return kqa(a)},$5=function(){this.g=[];
this.i=[]},a6=function(a,b){g.bq[a]=!0;
var c=g.$p();c&&c.publish.apply(c,arguments);g.bq[a]=!1},b6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.l=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Zm;this.g=this.i="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",mqa(this,a.capabilities||""),nqa(this,a.experiments||""),this.i=a.remoteControllerUrl||"",this.g=a.localChannelEncryptionKey||
"")},mqa=function(a,b){a.capabilities.clear();
(0,g.Xd)(b.split(","),g.Qa(bqa,oqa)).forEach(function(c){a.capabilities.add(c)})},nqa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},c6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},d6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},e6=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},pqa=function(a){return new c6(a)},f6=function(a){return g.Ka(a)?(0,g.ge)(a,pqa):[]},g6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},h6=function(a){return g.Ka(a)?"["+(0,g.ge)(a,g6).join(",")+"]":"null"},i6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},qqa=function(a){return(0,g.ge)(a,function(b){return{key:b.id,
name:b.name}})},j6=function(a,b){return g.Xa(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},k6=function(a,b){return g.Xa(a,function(c){return d6(c,b)})},l6=function(a){try{var b=(0,g.wt)(),c=(0,g.vt)();
b&&b.remove(a);c&&c.remove(a)}catch(d){}},rqa=function(){var a=(0,g.vt)();
a&&iqa(a,a.g.mf(!0))},m6=function(){var a=g.zt("yt-remote-connected-devices")||[];
g.qb(a);return a},sqa=function(a){if(0==a.length)return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.ge)(a,function(d,e){return 0==e?d:d.substring(c.length)})},n6=function(a){g.xt("yt-remote-connected-devices",a,86400)},p6=function(){if(o6)return o6;
var a=g.zt("yt-remote-device-id");a||(a=i6(),g.xt("yt-remote-device-id",a,31536E3));for(var b=m6(),c=1,d=a;g.$a(b,d);)c++,d=a+"#"+c;return o6=d},q6=function(){var a=m6(),b=p6();
g.$a(a,b);g.At()&&g.sb(a,b);a=sqa(a);if(0==a.length)try{g.ys("remote_sid")}catch(c){}else try{g.xs("remote_sid",a.join(","),-1)}catch(c){}},r6=function(){return g.zt("yt-remote-session-browser-channel")},s6=function(){return g.zt("yt-remote-local-screens")||[]},t6=function(){g.xt("yt-remote-lounge-token-expiration",!0,86400)},tqa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.ge)(s6(),function(d){return d.loungeToken}),c=(0,g.ge)(a,function(d){return d.loungeToken});
(0,g.lj)(c,function(d){return!g.$a(b,d)})&&t6();
g.xt("yt-remote-local-screens",a,31536E3)},uqa=function(a,b){g.xt("yt-remote-session-browser-channel",a);
g.xt("yt-remote-session-screen-id",b);var c=m6(),d=p6();g.$a(c,d)||c.push(d);n6(c);q6()},u6=function(a){a||(l6("yt-remote-session-screen-id"),l6("yt-remote-session-video-id"));
q6();a=m6();g.db(a,p6());n6(a)},w6=function(){if(!v6){var a=g.gp();
a&&(v6=new g.Ro(a))}return v6?!!v6.get("yt-remote-use-staging-server"):!1},x6=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},y6=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},A6=function(a){a.length?z6(a.shift(),function(){A6(a)}):B6()},vqa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},z6=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},B6=function(){var a=y6();
a&&a(!1,"No cast extension found")},C6=function(){if(wqa){var a=2,b=y6(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;z6("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",B6,c)}},xqa=function(){C6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);A6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},D6=function(a,b,c){g.A.call(this);
this.A=null!=c?(0,g.x)(a,c):a;this.Yc=b;this.u=(0,g.x)(this.uD,this);this.g=!1;this.i=0;this.l=this.Aa=null;this.o=[]},E6=function(){},F6=function(a,b,c,d){this.g=a;
this.l=b;this.C=c;this.A=d||1;this.o=45E3;this.ca=new g.qn(this);this.i=new g.Fg;this.i.setInterval(250)},H6=function(a,b,c){a.Yh=1;
a.Yf=K5(b.clone());a.sh=c;a.u=!0;G6(a,null)},I6=function(a,b,c,d,e){a.Yh=1;
a.Yf=K5(b.clone());a.sh=null;a.u=c;e&&(a.mA=!1);G6(a,d)},G6=function(a,b){a.Ii=(0,g.D)();
J6(a);a.Eg=a.Yf.clone();L5(a.Eg,"t",a.A);a.pl=0;a.uc=a.g.Qp(a.g.Xk()?b:null);0<a.xq&&(a.Yn=new g.Gl((0,g.x)(a.sB,a,a.uc),a.xq));a.ca.da(a.uc,"readystatechange",a.kM);var c=a.Zg?g.bc(a.Zg):{};a.sh?(a.Fo="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.uc.send(a.Eg,a.Fo,a.sh,c)):(a.Fo="GET",a.mA&&!g.Nd&&(c.Connection="close"),a.uc.send(a.Eg,a.Fo,null,c));a.g.Ae(1)},Q6=function(a,b,c){for(var d=!0;!a.Og&&a.pl<c.length;){var e=yqa(a,c);
if(e==K6){4==b&&(a.qg=4,L6(15),d=!1);break}else if(e==M6){a.qg=4;L6(16);d=!1;break}else N6(a,e)}4==b&&0==c.length&&(a.qg=1,L6(17),d=!1);a.De=a.De&&d;d||(O6(a),P6(a))},yqa=function(a,b){var c=a.pl,d=b.indexOf("\n",c);
if(-1==d)return K6;c=Number(b.substring(c,d));if(isNaN(c))return M6;d+=1;if(d+c>b.length)return K6;var e=b.substr(d,c);a.pl=d+c;return e},T6=function(a,b){a.Ii=(0,g.D)();
J6(a);var c=b?window.location.hostname:"";a.Eg=a.Yf.clone();g.kn(a.Eg,"DOMAIN",c);g.kn(a.Eg,"t",a.A);try{a.He=new ActiveXObject("htmlfile")}catch(n){O6(a);a.qg=7;L6(22);P6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in R6)k=R6[l];else if(l in S6)k=R6[l]=S6[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
R6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Rc(g.qc("b/12014412"),d+"</body></html>");a.He.open();a.He.write(g.Mc(c));a.He.close();a.He.parentWindow.m=(0,g.x)(a.AL,a);a.He.parentWindow.d=(0,g.x)(a.sz,a,!0);a.He.parentWindow.rpcClose=(0,g.x)(a.sz,a,!1);c=a.He.createElement("DIV");a.He.parentWindow.document.body.appendChild(c);d=g.Cc(a.Eg.toString());d=g.Yc(g.zc(d));d=g.Rc(g.qc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Sc(c,d);a.g.Ae(1)},J6=function(a){a.Et=(0,g.D)()+a.o;
U6(a,a.o)},U6=function(a,b){if(null!=a.Yi)throw Error("WatchDog timer not null");
a.Yi=V6((0,g.x)(a.KL,a),b)},W6=function(a){a.Yi&&(g.u.clearTimeout(a.Yi),a.Yi=null)},P6=function(a){a.g.tw()||a.Og||a.g.Ln(a)},O6=function(a){W6(a);
g.qf(a.Yn);a.Yn=null;a.i.stop();g.sn(a.ca);if(a.uc){var b=a.uc;a.uc=null;b.abort();b.dispose()}a.He&&(a.He=null)},N6=function(a,b){try{a.g.mz(a,b),a.g.Ae(4)}catch(c){}},Y6=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;X6(a,b,function(k){k?c(!0):g.u.setTimeout(function(){Y6(a,b,c,d,f)},f)})}},X6=function(a,b,c){var d=new Image;
d.onload=function(){try{Z6(d),c(!0)}catch(e){}};
d.onerror=function(){try{Z6(d),c(!1)}catch(e){}};
d.onabort=function(){try{Z6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{Z6(d),c(!1)}catch(e){}};
g.u.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
Y5(d,a)},Z6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},$6=function(a){this.g=a;
this.i=new E6},b7=function(a){var b=a7(a.g,a.nj,"/mail/images/cleardot.gif");
K5(b);Y6(b.toString(),5E3,(0,g.x)(a.BC,a),3,2E3);a.Ae(1)},d7=function(a){var b=a.g.F;
if(null!=b)L6(5),b?(L6(11),c7(a.g,a,!1)):(L6(12),c7(a.g,a,!0));else if(a.Gd=new F6(a,void 0,void 0,void 0),a.Gd.Zg=a.uq,b=a.g,b=a7(b,b.Xk()?a.Vj:null,a.wq),L6(5),!g.Ld||g.od(10))L5(b,"TYPE","xmlhttp"),I6(a.Gd,b,!1,a.Vj,!1);else{L5(b,"TYPE","html");var c=a.Gd;a=!!a.Vj;c.Yh=3;c.Yf=K5(b.clone());T6(c,a)}},e7=function(a,b,c){this.g=1;
this.i=[];this.o=[];this.u=new E6;this.D=a||null;this.F=null!=b?b:null;this.A=c||!1},zqa=function(a,b){this.g=a;
this.map=b;this.context=null},f7=function(a){g.sf.call(this,"statevent",a)},g7=function(a,b){g.sf.call(this,"timingevent",a);
this.size=b},h7=function(a){g.sf.call(this,"serverreachability",a)},l7=function(a){i7(a);
if(3==a.g){var b=a.Bk++,c=a.pm.clone();g.kn(c,"SID",a.l);g.kn(c,"RID",b);g.kn(c,"TYPE","terminate");j7(a,c);b=new F6(a,a.l,b,void 0);b.Yh=2;b.Yf=K5(c.clone());Y5(new Image,b.Yf.toString());b.Ii=(0,g.D)();J6(b)}k7(a)},n7=function(a){a.TC(1,0);
a.pm=a7(a,null,a.tq);m7(a)},i7=function(a){a.gg&&(a.gg.abort(),a.gg=null);
a.Vb&&(a.Vb.cancel(),a.Vb=null);a.qf&&(g.u.clearTimeout(a.qf),a.qf=null);o7(a);a.Dd&&(a.Dd.cancel(),a.Dd=null);a.ng&&(g.u.clearTimeout(a.ng),a.ng=null)},p7=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new zqa(a.QH++,b));2!=a.g&&3!=a.g||m7(a)},m7=function(a){a.Dd||a.ng||(a.ng=V6((0,g.x)(a.rz,a),0),a.Rh=0)},s7=function(a,b){if(1==a.g){if(!b){a.Bk=Math.floor(1E5*Math.random());
var c=a.Bk++,d=new F6(a,"",c,void 0);d.Zg=null;var e=q7(a),f=a.pm.clone();g.kn(f,"RID",c);g.kn(f,"CVER","1");j7(a,f);H6(d,f,e);a.Dd=d;a.g=2}}else 3==a.g&&(b?r7(a,b):0==a.i.length||a.Dd||r7(a))},r7=function(a,b){if(b)if(6<a.Pg){a.i=a.o.concat(a.i);
a.o.length=0;var c=a.Bk-1;var d=q7(a)}else c=b.C,d=b.sh;else c=a.Bk++,d=q7(a);var e=a.pm.clone();g.kn(e,"SID",a.l);g.kn(e,"RID",c);g.kn(e,"AID",a.li);j7(a,e);c=new F6(a,a.l,c,a.Rh+1);c.Zg=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Dd=c;H6(c,e,d)},j7=function(a,b){if(a.Vc){var c=a.Vc.Tv();
c&&g.Kb(c,function(d,e){g.kn(b,e,d)})}},q7=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Pg&&0<b){var d=a.i[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.i[e].g,k=a.i[e].map;f=6>=a.Pg?e:f-d;try{g.Kb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.o=a.o.concat(a.i.splice(0,b));
return c.join("&")},t7=function(a){a.Vb||a.qf||(a.C=1,a.qf=V6((0,g.x)(a.qz,a),0),a.Kh=0)},v7=function(a){if(a.Vb||a.qf||3<=a.Kh)return!1;
a.C++;a.qf=V6((0,g.x)(a.qz,a),u7(a,a.Kh));a.Kh++;return!0},c7=function(a,b,c){a.Do=c;
a.Me=b.Af;a.A||n7(a)},o7=function(a){null!=a.Tg&&(g.u.clearTimeout(a.Tg),a.Tg=null)},u7=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},x7=function(a,b){if(2==b||9==b){var c=null;
a.Vc&&(c=null);var d=(0,g.x)(a.QM,a);c||(c=new g.bn("//www.google.com/images/cleardot.gif"),K5(c));X6(c.toString(),1E4,d)}else L6(2);w7(a,b)},w7=function(a,b){a.g=0;
a.Vc&&a.Vc.Vu(b);k7(a);i7(a)},k7=function(a){a.g=0;
a.Me=-1;if(a.Vc)if(0==a.o.length&&0==a.i.length)a.Vc.Ep();else{g.gb(a.o);var b=g.gb(a.i);a.o.length=0;a.i.length=0;a.Vc.Ep(b)}},a7=function(a,b,c){var d=g.ln(c);
if(""!=d.g)b&&g.dn(d,b+"."+d.g),g.en(d,d.u);else{var e=window.location;d=lqa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Dj&&g.Kb(a.Dj,function(f,k){g.kn(d,k,f)});
g.kn(d,"VER",a.Pg);j7(a,d);return d},V6=function(a,b){if(!g.Ma(a))throw Error("Fn must not be null and must be a function");
return g.u.setTimeout(function(){a()},b)},L6=function(a){y7.dispatchEvent(new f7(y7,a))},z7=function(){},Aqa=function(a,b){this.action=a;
this.params=b||{}},A7=function(a,b){g.A.call(this);
this.g=new g.J(this.sL,0,this);g.C(this,this.g);this.Yc=5E3;this.i=0;if(g.Ma(a))b&&(a=(0,g.x)(a,b));else if(a&&g.Ma(a.handleEvent))a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.l=a},B7=function(a,b,c){this.H=a;
this.A=b;this.l=new g.Qo;this.i=new A7(this.uM,this);this.g=null;this.ib=!1;this.u=null;this.F="";this.D=this.o=0;this.C=[];this.I=c||!1},Bqa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Do,sessionId:a.g.l,arrayId:a.g.li}},C7=function(a,b){a.D=b||0;
a.i.stop();a.g&&(3==a.g.g&&s7(a.g),l7(a.g));a.D=0},D7=function(a){return!!a.g&&3==a.g.g},Cqa=function(a,b){(a.A.loungeIdToken=b)||a.i.stop()},E7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.i=!0;a=a||document.location.href;var b=Number(g.Sg(4,a))||"";b&&(this.port=":"+b);this.domain=g.Tg(a)||"";a=g.Ib;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Hb(a,"10.0")&&(this.i=!1))},F7=function(a,b){var c=a.g;
if(g.Ca(void 0)?0:a.i)c="https://"+a.domain+a.port+a.g;return g.bh(c+b,{})},G7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Qa(a.o,d,!0),onError:g.Qa(a.l,e),ne:g.Qa(a.u,e)};c&&(a.vb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Uq(b,a)},Dqa=function(){var a=H7;
I7();J7.push(a);K7(J7)},L7=function(a,b){I7();
var c=J7,d=Eqa(a,String(b));0==c.length?Fqa(d):(K7(c),(0,g.y)(c,function(e){e(d)}))},I7=function(){J7||(J7=g.w("yt.mdx.remote.debug.handlers_")||[],g.Ga("yt.mdx.remote.debug.handlers_",J7,void 0))},Fqa=function(a){var b=(M7+1)%50;
M7=b;N7[b]=a;O7||(O7=49==b)},K7=function(a){var b=N7;
if(b[0]){var c=M7,d=O7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.y)(a,function(f){f(e)})}while(d!=c);
N7=Array(50);M7=-1;O7=!1}},Eqa=function(a,b){var c=((0,g.D)()-Gqa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},P7=function(a){g.N.call(this);
this.C=a;this.g=[]},Q7=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},Hqa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Xd)(a.g,function(f){return!!j6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=Q7(a,b[d])||c;return c},Iqa=function(a,b){var c=a.g.length;
a.g=(0,g.Xd)(a.g,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.g.length<c},R7=function(a,b,c,d){g.N.call(this);
this.A=a;this.u=b;this.l=c;this.o=d;this.i=0;this.g=null;this.Aa=NaN},T7=function(a){P7.call(this,"LocalScreenService");
this.l=a;this.i=NaN;S7(this);this.info("Initializing with "+h6(this.g))},U7=function(a){if(a.g.length){var b=(0,g.ge)(a.g,function(d){return d.id}),c=F7(a.l,"/pairing/get_lounge_token_batch");
G7(a.l,c,{screen_ids:b.join(",")},(0,g.x)(a.ED,a),(0,g.x)(a.DD,a))}},S7=function(a){var b=f6(s6());
b=(0,g.Xd)(b,function(c){return!c.uuid});
return Hqa(a,b)},V7=function(a,b){tqa((0,g.ge)(a.g,e6));
b&&t6()},X7=function(a,b){g.N.call(this);
this.A=b;var c=g.zt("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.A(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.$a(c,l)}this.g=d;this.u=a;this.l=this.o=NaN;this.i=null;W7("Initialized with "+g.Kg(this.g))},Y7=function(a,b,c){var d=F7(a.u,"/pairing/get_screen_availability");
G7(a.u,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},Z7=function(a,b){a:if(X5(b)!=X5(a.g))var c=!1;
else{c=g.Rb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(W7("Updated online screens: "+g.Kg(a.g)),a.g=b,a.N("screenChange"));Jqa(a)},$7=function(a){isNaN(a.l)||g.Zp(a.l);
a.l=g.Xp((0,g.x)(a.Is,a),0<a.o&&a.o<(0,g.D)()?2E4:1E4)},W7=function(a){L7("OnlineScreenService",a)},Kqa=function(a){var b={};
(0,g.y)(a.A(),function(c){c.token?b[c.token]=c.id:this.Hb("Requesting availability of screen w/o lounge token.")});
return b},Jqa=function(a){a=g.Rb(g.Lb(a.g,function(b){return b}));
g.qb(a);a.length?g.xt("yt-remote-online-screen-ids",a.join(","),60):l6("yt-remote-online-screen-ids")},a8=function(a){P7.call(this,"ScreenService");
this.A=a;this.i=this.l=null;this.o=[];this.u={};Lqa(this)},Nqa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.u[b]);var k=a.Qd();if(k=(c?k6(k,c):null)||k6(k,b)){k.uuid=b;var l=b8(a,k);Y7(a.i,l,function(m){e(m?l:null)})}else c?Mqa(a,c,(0,g.x)(function(m){var n=b8(this,new c6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));Y7(this.i,n,function(p){e(p?n:null)})},a),f):e(null)},Oqa=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},Mqa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={vb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Uq(F7(a.A,"/pairing/get_lounge_token_batch"),e)},Pqa=function(a){a.g=a.l.Qd();
var b=a.u,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+h6(a.g))},Lqa=function(a){c8(a);
a.l=new T7(a.A);a.l.subscribe("screenChange",(0,g.x)(a.MD,a));Pqa(a);a.o=f6(g.zt("yt-remote-automatic-screen-cache")||[]);c8(a);a.info("Initializing automatic screens: "+h6(a.o));a.i=new X7(a.A,(0,g.x)(a.Qd,a,!0));a.i.subscribe("screenChange",(0,g.x)(function(){this.N("onlineScreenChange")},a))},b8=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=k6(a.o,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.o.push(b),g.xt("yt-remote-automatic-screen-cache",(0,g.ge)(a.o,e6)));c8(a);a.u[b.uuid]=b.id;g.xt("yt-remote-device-id-map",a.u,31536E3);return b},c8=function(a){a.u=g.zt("yt-remote-device-id-map")||{}},d8=function(a,b,c){g.N.call(this);
this.P=c;this.F=a;this.i=b;this.l=null},e8=function(a,b){L7(a.P,b)},f8=function(a,b){d8.call(this,a,b,"CastSession");
this.g=null;this.o=0;this.A=(0,g.x)(this.vN,this);this.u=(0,g.x)(this.VL,this);this.o=g.Xp((0,g.x)(function(){Qqa(this,null)},this),12E4)},Rqa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Kg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ha,(0,g.x)(function(){e8(this,"Failed to send message: getMdxSessionStatus.")},a)):e8(a,"Sending yt message without session: "+g.Kg(b))},Qqa=function(a,b){g.Zp(a.o);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.l||a.l.id!=b){var c=(0,g.x)(a.Nn,a),d=(0,g.x)(a.Td,a);a.kw(b,c,d,5)}}else a.Td(Error("Waiting for session status timed out."))},g8=function(a,b,c){d8.call(this,a,b,"DialSession");
this.o=this.D=null;this.H="";this.M=c;this.u=null;this.C=g.Ha;this.A=NaN;this.I=(0,g.x)(this.yN,this);this.g=g.Ha},Sqa=function(a){a.g=a.F.xB(a.H,a.i.label,a.i.friendlyName,(0,g.x)(function(b){this.g=g.Ha;
this.Nn(b)},a),(0,g.x)(function(b){this.g=g.Ha;
this.Td(b)},a))},Tqa=function(a){var b={};
b.pairingCode=a.H;b.theme=a.M;if(a.u){var c=a.u.currentTime||0;b.v=a.u.videoId;b.t=c}w6()&&(b.env_useStageMdx=1);return g.$g(b)},h8=function(a,b){d8.call(this,a,b,"ManualSession");
this.g=g.Xp((0,g.x)(this.ni,this,null),150)},i8=function(a,b,c,d){g.N.call(this);
this.i=a;this.C=b||"233637DE";this.A=c||"cl";this.D=d||!1;this.g=null;this.u=!1;this.l=[];this.o=(0,g.x)(this.BK,this)},Uqa=function(a,b){return b?g.Xa(a.l,function(c){return d6(b,c.label)},a):null},j8=function(a){L7("Controller",a)},H7=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},k8=function(a){return a.u||!!a.l.length||!!a.g},l8=function(a,b,c){b!=a.g&&(g.qf(a.g),(a.g=b)?(c?a.N("yt-remote-cast2-receiver-resumed",b.i):a.N("yt-remote-cast2-receiver-selected",
b.i),b.subscribe("sessionScreen",(0,g.x)(a.pz,a,b)),b.l?a.N("yt-remote-cast2-session-change",b.l):c&&a.g.ni(null)):a.N("yt-remote-cast2-session-change",null))},Vqa=function(a){var b=a.i.wB(),c=a.g&&a.g.i;
a=(0,g.ge)(b,function(d){c&&d6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=Uqa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},ara=function(a,b,c,d,e,f,k){Wqa()?Xqa(b,e,f,k)&&(n8(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?Yqa(a,c):(window.__onGCastApiAvailable=function(l,m){l?Yqa(a,c):(o8("Failed to load cast API: "+m),p8(!1),n8(!1),l6("yt-remote-cast-available"),l6("yt-remote-cast-receiver"),Zqa(),c(!1))},d?g.jq("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?xqa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?B6():(C6(),A6($qa.map(vqa))))):m8("Cannot initialize because not running Chrome")},Zqa=function(){m8("dispose");
var a=q8();a&&a.dispose();g.Ga("yt.mdx.remote.cloudview.instance_",null,void 0);bra(!1);g.eq(r8);r8.length=0},s8=function(){return!!g.zt("yt-remote-cast-installed")},cra=function(){var a=g.zt("yt-remote-cast-receiver");
return a?a.friendlyName:null},dra=function(){m8("clearCurrentReceiver");
l6("yt-remote-cast-receiver")},era=function(){return s8()?q8()?q8().getCastSession():(o8("getCastSelector: Cast is not initialized."),null):(o8("getCastSelector: Cast API is not installed!"),null)},u8=function(){s8()?q8()?t8()?(m8("Requesting cast selector."),q8().requestSession()):(m8("Wait for cast API to be ready to request the session."),r8.push(g.dq("yt-remote-cast2-api-ready",u8))):o8("requestCastSelector: Cast is not initialized."):o8("requestCastSelector: Cast API is not installed!")},v8=
function(a,b){t8()?q8().setConnectedScreenStatus(a,b):o8("setConnectedScreenStatus called before ready.")},Wqa=function(){var a=0<=g.Ib.search(/ (CrMo|Chrome|CriOS)\//);
return g.gx||a},fra=function(a,b){q8().init(a,b)},Xqa=function(a,b,c,d){var e=!1;
q8()||(a=new i8(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.xt("yt-remote-cast-available",f);a6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){m8("onReceiverSelected: "+f.friendlyName);
g.xt("yt-remote-cast-receiver",f);a6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){m8("onReceiverResumed: "+f.friendlyName);
g.xt("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){m8("onSessionChange: "+g6(f));
f||l6("yt-remote-cast-receiver");a6("yt-remote-cast2-session-change",f)}),g.Ga("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
m8("cloudview.createSingleton_: "+e);return e},q8=function(){return g.w("yt.mdx.remote.cloudview.instance_")},Yqa=function(a,b){p8(!0);
n8(!1);fra(a,function(c){c?(bra(!0),g.gq("yt-remote-cast2-api-ready")):(o8("Failed to initialize cast API."),p8(!1),l6("yt-remote-cast-available"),l6("yt-remote-cast-receiver"),Zqa());b(c)})},m8=function(a){L7("cloudview",a)},o8=function(a){L7("cloudview",a)},p8=function(a){m8("setCastInstalled_ "+a);
g.xt("yt-remote-cast-installed",a)},t8=function(){return!!g.w("yt.mdx.remote.cloudview.apiReady_")},bra=function(a){m8("setApiReady_ "+a);
g.Ga("yt.mdx.remote.cloudview.apiReady_",a,void 0)},n8=function(a){g.Ga("yt.mdx.remote.cloudview.initializing_",a,void 0)},w8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.A=this.C=0;this.g=null;this.hasNext=this.Ne=!1;this.F=this.D=this.i=this.o=0;this.l=NaN;this.u=!1;this.reset(a)},x8=function(a){a.audioTrackId=null;
a.g=null;a.playerState=-1;a.Ne=!1;a.hasNext=!1;a.C=0;a.A=(0,g.D)();a.o=0;a.i=0;a.D=0;a.F=0;a.l=NaN;a.u=!1},y8=function(a){return 1==a.playerState?((0,g.D)()-a.A)/1E3:0},z8=function(a,b){a.C=b;
a.A=(0,g.D)()},A8=function(a){switch(a.playerState){case 1:case 1081:return((0,g.D)()-a.A)/1E3+a.C;
case -1E3:return 0}return a.C},B8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&x8(a)},C8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.cc(a.g);b.hasPrevious=a.Ne;b.hasNext=a.hasNext;b.playerTime=a.C;b.playerTimeAt=a.A;b.seekableStart=a.o;b.seekableEnd=a.i;b.duration=a.D;b.loadedTime=a.F;b.liveIngestionTime=a.l;return b},E8=function(a,b){g.N.call(this);
this.g=0;this.o=a;this.A=[];this.u=new $5;this.l=this.i=null;this.F=(0,g.x)(this.yI,this);this.C=(0,g.x)(this.Ek,this);this.D=(0,g.x)(this.xI,this);this.H=(0,g.x)(this.MI,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Ht,this),gra(this))):c=3;0!=c&&(b?this.Ht(c):g.Xp((0,g.x)(function(){this.Ht(c)},this),0));
var d=era();d&&D8(this,d);this.subscribe("yt-remote-cast2-session-change",this.H)},F8=function(a){return new w8(a.o.getPlayerContextData())},gra=function(a){(0,g.y)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.A.push(this.o.subscribe(b,g.Qa(this.yK,b),this))},a)},hra=function(a){(0,g.y)(a.A,function(b){this.o.unsubscribeByKey(b)},a);
a.A.length=0},G8=function(a,b){var c=a.u;
50>c.g.length+c.i.length&&a.u.i.push(b)},I8=function(a,b,c){var d=F8(a);
z8(d,c);-1E3!=d.playerState&&(d.playerState=b);H8(a,d)},J8=function(a,b,c){a.o.sendMessage(b,c)},H8=function(a,b){hra(a);
a.o.setPlayerContextData(C8(b));gra(a)},D8=function(a,b){a.l&&(a.l.removeUpdateListener(a.F),a.l.removeMediaListener(a.C),a.Ek(null));
a.l=b;a.l&&(L7("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.F),a.l.addMediaListener(a.C),a.l.media.length&&a.Ek(a.l.media[0]))},ira=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=F8(a);b.contentId!=d.videoId&&L7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;z8(d,a.i.getEstimatedTime());H8(a,d)}else L7("CP","No cast media video. Ignoring state update.")},K8=function(a,b,c){return(0,g.x)(function(d){this.Hb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Hb("Retrying "+b+" using MDx browser channel."),J8(this,b,c))},a)},L8=function(a,b,c){g.N.call(this);
this.u=NaN;this.I=!1;this.D=this.C=this.F=this.H=NaN;this.P=[];this.o=this.A=this.l=this.Oa=this.g=null;this.R=a;this.P.push(g.bs(window,"beforeunload",(0,g.x)(this.xD,this)));this.i=[];this.Oa=new w8;this.M=b.id;this.g=jra(this,c);this.g.subscribe("handlerOpened",this.CI,this);this.g.subscribe("handlerClosed",this.zI,this);this.g.subscribe("handlerError",this.AI,this);this.g.subscribe("handlerMessage",this.BI,this);Cqa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Oa.videoId;
g.At()&&g.xt("yt-remote-session-video-id",d)},this)},M8=function(a){L7("conn",a)},jra=function(a,b){return new B7(F7(a.R,"/bc"),b)},N8=function(a,b){a.N("proxyStateChange",b)},kra=function(a){a.u=g.Xp((0,g.x)(function(){M8("Connecting timeout");
this.Oh(1)},a),2E4)},O8=function(a){g.Zp(a.u);
a.u=NaN},P8=function(a){g.Zp(a.H);
a.H=NaN},lra=function(a){Q8(a);
a.F=g.Xp((0,g.x)(function(){R8(this,"getNowPlaying")},a),2E4)},Q8=function(a){g.Zp(a.F);
a.F=NaN},nra=function(a,b){b&&(O8(a),P8(a));
b==(D7(a.g)&&isNaN(a.u))?b&&(N8(a,1),R8(a,"getSubtitlesTrack")):b?(a.iw()&&a.Oa.reset(),N8(a,1),R8(a,"getNowPlaying"),mra(a)):a.Oh(1)},ora=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Oa.videoId&&(g.Xb(b.params)?a.Oa.g=null:a.Oa.g=b.params,a.N("remotePlayerChange"))},pra=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Oa.listId=b.params.listId||a.Oa.listId;B8(a.Oa,c,d);a.N("remoteQueueChange")},rra=function(a,b){b.params=b.params||{};
pra(a,b);qra(a,b);a.N("autoplayDismissed")},qra=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
z8(a.Oa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Oa.playerState&&(c=-1E3);a.Oa.playerState=c;c=Number(b.params.loadedTime);a.Oa.F=isNaN(c)?0:c;c=Number(b.params.duration);a.Oa.D=isNaN(c)?0:c;c=a.Oa;var d=Number(b.params.liveIngestionTime);c.l=d;c.u=isNaN(d)?!1:!0;c=a.Oa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.o=isNaN(d)?0:d;c.i=isNaN(e)?0:e;1==a.Oa.playerState?lra(a):Q8(a);a.N("remotePlayerChange")},sra=function(a,b){if(-1E3!=
a.Oa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Oa.playerState=c;c=parseInt(b.params.currentTime,10);z8(a.Oa,isNaN(c)?0:c);a.N("remotePlayerChange")}},tra=function(a,b){var c="true"==b.params.muted;
a.Oa.volume=parseInt(b.params.volume,10);a.Oa.muted=c;a.N("remotePlayerChange")},ura=function(a,b){a.A=b.params.videoId;
a.N("nowAutoplaying",parseInt(b.params.timeout,10))},vra=function(a,b){var c="true"==b.params.hasNext;
a.Oa.Ne="true"==b.params.hasPrevious;a.Oa.hasNext=c;a.N("previousNextChange")},mra=function(a){g.Zp(a.D);
a.D=g.Xp((0,g.x)(a.Oh,a,1),864E5)},R8=function(a,b,c){c?M8("Sending: action="+b+", params="+g.Kg(c)):M8("Sending: action="+b);
a.g.sendMessage(b,c)},S8=function(a){P7.call(this,"ScreenServiceProxy");
this.Xc=a;this.i=[];this.i.push(this.Xc.$_s("screenChange",(0,g.x)(this.tN,this)));this.i.push(this.Xc.$_s("onlineScreenChange",(0,g.x)(this.dK,this)))},Ara=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.Pp("MDX_CONFIG")||b;rqa();q6();T8||(T8=new E7(b?b.loungeApiHost:void 0),w6()&&(T8.g="/api/loungedev"));U8||(U8=g.w("yt.mdx.remote.deferredProxies_")||[],g.Ga("yt.mdx.remote.deferredProxies_",U8,void 0));wra();var c=V8();if(!c){var d=new a8(T8);g.Ga("yt.mdx.remote.screenService_",d,void 0);c=V8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);ara(a,d,function(m){m?W8()&&v8(W8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){a6("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.w("yt.mdx.remote.initialized_")&&(g.Ga("yt.mdx.remote.initialized_",!0,void 0),X8("Initializing: "+g.Kg(b)),Y8.push(g.dq("yt-remote-cast2-availability-change",function(){a6("yt-remote-receiver-availability-change")})),Y8.push(g.dq("yt-remote-cast2-receiver-selected",function(){Z8(null);
a6("yt-remote-auto-connect","cast-selector-receiver")})),Y8.push(g.dq("yt-remote-cast2-receiver-resumed",function(){a6("yt-remote-receiver-resumed","cast-selector-receiver")})),Y8.push(g.dq("yt-remote-cast2-session-change",xra)),Y8.push(g.dq("yt-remote-connection-change",function(m){m?v8(W8(),"YouTube TV"):$8()||(v8(null,null),dra())})),a=a9(),b.isAuto&&(a.id+="#dial"),g.Lq("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),X8(" -- with channel params: "+
g.Kg(a)),yra(a),c.start(),W8()||zra())},Cra=function(){var a=Bra();
s8()&&g.zt("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},Bra=function(){var a=V8().Xc.$_gos();
var b=b9();b&&c9()&&(j6(a,b)||a.push(b));return qqa(a)},d9=function(){var a=Dra();
!a&&s8()&&cra()&&(a={key:"cast-selector-receiver",name:cra()});return a},Dra=function(){var a=Bra(),b=b9();
b||(b=$8());return g.Xa(a,function(c){return b&&d6(b,c.key)?!0:!1})},b9=function(){var a=W8();
if(!a)return null;var b=V8().Qd();return k6(b,a)},xra=function(a){X8("remote.onCastSessionChange_: "+g6(a));
if(a){var b=b9();b&&b.id==a.id?v8(b.id,"YouTube TV"):(b&&e9(),f9(a,1))}else c9()&&e9()},e9=function(){t8()?q8().stopSession():o8("stopSession called before API ready.");
var a=c9();a&&(a.disconnect(1),g9(null))},h9=function(){var a=c9();
return!!a&&3!=a.getProxyState()},X8=function(a){L7("remote",a)},V8=function(){if(!i9){var a=g.w("yt.mdx.remote.screenService_");
i9=a?new S8(a):null}return i9},W8=function(){return g.w("yt.mdx.remote.currentScreenId_")},Era=function(a){g.Ga("yt.mdx.remote.currentScreenId_",a,void 0)},Fra=function(){return g.w("yt.mdx.remote.connectData_")},Z8=function(a){g.Ga("yt.mdx.remote.connectData_",a,void 0)},c9=function(){return g.w("yt.mdx.remote.connection_")},g9=function(a){var b=c9();
Z8(null);a||Era("");g.Ga("yt.mdx.remote.connection_",a,void 0);U8&&((0,g.y)(U8,function(c){c(a)}),U8.length=0);
b&&!a?a6("yt-remote-connection-change",!1):!b&&a&&a6("yt-remote-connection-change",!0)},$8=function(){var a=g.At();
if(!a)return null;var b=V8().Qd();return k6(b,a)},f9=function(a,b){b9()&&b9();
if(j9)k9=a;else{Era(a.id);var c=new L8(T8,a,a9());c.connect(b,Fra());c.subscribe("beforeDisconnect",function(d){a6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){c9()&&g9(null)});
g9(c)}},zra=function(){var a=$8();
a?(X8("Resume connection to: "+g6(a)),f9(a,0)):(u6(),dra(),X8("Skipping connecting because no session screen found."))},wra=function(){var a=a9();
if(g.Xb(a)){a=p6();var b=g.zt("yt-remote-session-name")||"",c=g.zt("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ga("yt.mdx.remote.channelParams_",a,void 0)}},a9=function(){return g.w("yt.mdx.remote.channelParams_")||{}},yra=function(a){a?(g.xt("yt-remote-session-app",a.app),g.xt("yt-remote-session-name",a.name)):(l6("yt-remote-session-app"),l6("yt-remote-session-name"));
g.Ga("yt.mdx.remote.channelParams_",a,void 0)},l9=function(a,b,c){g.A.call(this);
this.u=a;this.i=b;this.l=new g.Ls(this);g.C(this,this.l);this.l.K(b,"onCaptionsTrackListChanged",this.xJ);this.l.K(b,"captionschanged",this.wI);this.l.K(b,"captionssettingschanged",this.KA);this.l.K(b,"videoplayerreset",this.On);this.l.K(b,"mdxautoplaycancel",this.AC);this.R=this.l.K(b,"onVolumeChange",this.az);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.lz,this);c.subscribe("remotePlayerChange",this.Gk,this);c.subscribe("remoteQueueChange",this.On,this);c.subscribe("autoplayUpNext",this.Py,
this);c.subscribe("previousNextChange",this.iz,this);c.subscribe("nowAutoplaying",this.ez,this);c.subscribe("autoplayDismissed",this.Oy,this);this.suggestion=null;this.F=new g.EC(64);this.o=new g.J(this.IA,500,this);g.C(this,this.o);this.A=new g.J(this.JA,1E3,this);g.C(this,this.A);this.I=new D6(this.ZM,0,this);g.C(this,this.I);this.C={};this.P=new g.J(this.kB,1E3,this);g.C(this,this.P);this.H=new g.Gl(this.TF,1E3,this);g.C(this,this.H);this.M=g.Ha;this.KA();this.On();this.Gk()},m9=function(a,b){a.u.Mc(b,
a.i.getVideoData().lengthSeconds)},Gra=function(a){m9(a,0);
a.o.stop();n9(a,new g.EC(64))},p9=function(a,b){if(o9(a)&&!a.D){var c=null;
b&&(c={style:a.i.getSubtitlesUserSettings()},g.ec(c,b));a.g.zA(a.i.getVideoData(1).videoId,c);a.C=F8(a.g).g}},q9=function(a,b){var c=a.i.getPlaylist();
if(c){var d=c.Sa;var e=c.listId.toString()}c=a.i.getVideoData(1);a.g.playVideo(c.videoId,b,d,e,c.playerParams,c.Ef,W5(c));n9(a,new g.EC(1))},Hra=function(a,b){if(b){var c=a.i.getOption("captions","tracklist",{XQ:1});
c&&c.length?(a.i.setOption("captions","track",b),a.D=!1):(a.i.loadModule("captions"),a.D=!0)}else a.i.setOption("captions","track",{})},o9=function(a){return F8(a.g).videoId==a.i.getVideoData(1).videoId},n9=function(a,b){a.A.stop();
var c=a.F;if(!g.KC(c,b)){var d=g.T(b,2);d!=g.T(a.F,2)&&g.BK(a.i,d);a.F=b;Ira(a.u,c,b)}},r9=function(){g.W.call(this,{B:"div",
G:"ytp-mdx-popup-dialog",L:{role:"dialog"},J:[{B:"div",G:"ytp-mdx-popup-dialog-inner-content",J:[{B:"div",G:"ytp-mdx-popup-title",V:"\u4f60\u5df2\u767b\u51fa\u5e33\u6236"},{B:"div",G:"ytp-mdx-popup-description",V:"\u4f60\u89c0\u770b\u7684\u5f71\u7247\u53ef\u80fd\u6703\u65b0\u589e\u81f3\u96fb\u8996\u7684\u89c0\u770b\u8a18\u9304\uff0c\u4e26\u5f71\u97ff\u7cfb\u7d71\u5728\u96fb\u8996\u4e0a\u63a8\u85a6\u7684\u5167\u5bb9\u3002\u5982\u8981\u907f\u514d\u9019\u7a2e\u60c5\u6cc1\uff0c\u8acb\u6309\u4e00\u4e0b [\u53d6\u6d88] \u4e26\u5728\u96fb\u8166\u4e0a\u767b\u5165 YouTube\u3002"},
{B:"div",G:"ytp-mdx-privacy-popup-buttons",J:[{B:"button",W:["ytp-button","ytp-mdx-privacy-popup-cancel"],V:"\u53d6\u6d88"},{B:"button",W:["ytp-button","ytp-mdx-privacy-popup-confirm"],V:"\u78ba\u8a8d"}]}]}]});this.l=new g.tQ(this,250);g.C(this,this.l);this.C=this.i["ytp-mdx-privacy-popup-cancel"];this.K(this.C,"click",this.o);this.u=this.i["ytp-mdx-privacy-popup-confirm"];this.K(this.u,"click",this.A)},s9=function(a){g.W.call(this,{B:"div",
G:"ytp-remote",J:[{B:"div",G:"ytp-remote-display-status",J:[{B:"div",G:"ytp-remote-display-status-icon",J:[g.IP()]},{B:"div",G:"ytp-remote-display-status-text",V:"{{statustext}}"}]}]});this.l=new g.tQ(this,250);g.C(this,this.l);this.o=a;this.K(a,"presentingplayerstatechange",this.u);Jra(this,g.xK(a))},Jra=function(a,b){if(3==a.o.getPresentingPlayerType()){var c={RECEIVER_NAME:a.o.getOption("remote","currentReceiver").name};
c=g.T(b,128)?g.HN("\u300c$RECEIVER_NAME\u300d\u767c\u751f\u932f\u8aa4",c):g.LC(b)||g.T(b,4)?g.HN("\u6b63\u5728\u300c$RECEIVER_NAME\u300d\u4e0a\u64ad\u653e",c):g.HN("\u5df2\u9023\u7dda\u81f3\u300c$RECEIVER_NAME\u300d",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},t9=function(a,b){g.eU.call(this,"\u64ad\u653e\u87a2\u5e55\uff1a",0,a,b);
this.l=a;this.F={};this.K(a,"onMdxReceiversChange",this.I);this.K(a,"presentingplayerstatechange",this.I);this.I()},u9=function(a){g.$K.call(this,a);
this.i={key:i6(),name:"\u9019\u53f0\u96fb\u8166"};this.u=null;this.o=[];this.F=this.g=null;this.C=[this.i];this.l=this.i;this.pk=new g.EC(64);this.I=0;this.Um=-1;if(!g.dz(g.X(this.player))){a=this.player;var b=g.yD(a);b&&(b=b.xn())&&(b=new t9(a,b),g.C(this,b));b=new s9(a);g.C(this,b);g.MK(a,b.element,4);this.H=new r9;g.C(this,this.H);g.MK(a,this.H.element,4);this.D=!!$8()}this.A=null},v9=function(a){a.A&&(a.player.removeEventListener("presentingplayerstatechange",a.A),a.A=null)},Ira=function(a,b,
c){a.pk=c;
a.player.N("presentingplayerstatechange",new g.PD(c,b))},w9=function(a,b){if(b.key!=a.l.key)if(b.key==a.i.key)e9();
else{var c;if(c=g.O(g.X(a.player).experiments,"mdx_enable_privacy_disclosure_ui"))c=g.Pp("PLAYER_CONFIG"),c=!(c&&c.args&&void 0!==c.args.authuser||g.Pp("SESSION_INDEX")||g.Pp("LOGGED_IN"));c&&!a.D&&(g.LC(g.xK(a.player))||(a.A=(0,g.x)(a.bM,a),a.player.addEventListener("presentingplayerstatechange",a.A)),a.player.pauseVideo(),a.H.l.show(),c9()||(j9=!0));a.l=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(d||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<
f.getLength();l++)k[l]=f.sa(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Ef,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(c=W5(c))&&(d.locationInfo=c);c=d}else c=null;X8("Connecting to: "+g.Kg(b));"cast-selector-receiver"==b.key?(Z8(c||null),t8()?q8().setLaunchParams(c||null):o8("setLaunchParams called before ready.")):!c&&h9()&&W8()==b.key?a6("yt-remote-connection-change",!0):(e9(),
Z8(c||null),c=V8().Qd(),(c=k6(c,b.key))&&f9(c,1))}},gqa=/^https?$/i,Kra=["POST",
"PUT"];g.Sa(U5,g.Sf);g.h=U5.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.D+"; newUri="+a);b=b?b.toUpperCase():"GET";this.D=a;this.l="";this.u=0;this.Y=b;this.R=!1;this.i=!0;this.g=this.M?M5(this.M):M5(g.fZ);this.P=this.M?this.M.getOptions():g.fZ.getOptions();this.g.onreadystatechange=(0,g.x)(this.ww,this);try{J5(N5(this,"Opening Xhr")),this.aa=!0,this.g.open(b,String(a),!0),this.aa=!1}catch(f){J5(N5(this,"Error opening Xhr: "+f.message));R5(this,f);return}a=
c||"";var e=this.headers.clone();d&&dqa(d,function(f,k){e.set(k,f)});
d=g.Xa(e.Od(),eqa);c=g.u.FormData&&a instanceof g.u.FormData;!g.$a(Kra,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.g.setRequestHeader(k,f)},this);
this.X&&(this.g.responseType=this.X);"withCredentials"in this.g&&this.g.withCredentials!==this.T&&(this.g.withCredentials=this.T);try{O5(this),0<this.A&&(this.I=fqa(this.g),J5(N5(this,"Will abort after "+this.A+"ms if incomplete, xhr2 "+this.I)),this.I?(this.g.timeout=this.A,this.g.ontimeout=(0,g.x)(this.xw,this)):this.F=g.Gg(this.xw,this.A,this)),J5(N5(this,"Sending request")),this.C=!0,this.g.send(a),this.C=!1}catch(f){J5(N5(this,"Send error: "+f.message)),R5(this,f)}};
g.h.xw=function(){"undefined"!=typeof g.JY&&this.g&&(this.l="Timed out after "+this.A+"ms, aborting",this.u=8,N5(this,this.l),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.i&&(N5(this,"Aborting"),this.i=!1,this.o=!0,this.g.abort(),this.o=!1,this.u=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),Q5(this))};
g.h.U=function(){this.g&&(this.i&&(this.i=!1,this.o=!0,this.g.abort(),this.o=!1),Q5(this,!0));U5.bb.U.call(this)};
g.h.ww=function(){this.fa()||(this.aa||this.C||this.o?T5(this):this.AK())};
g.h.AK=function(){T5(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<S5(this)?this.g.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return g.Da(this.l)?this.l:String(this.l)};
var S6={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},R6={"'":"\\'"},Lra={};g.h=$5.prototype;g.h.isEmpty=function(){return 0==this.g.length&&0==this.i.length};
g.h.clear=function(){this.g=[];this.i=[]};
g.h.contains=function(a){return g.$a(this.g,a)||g.$a(this.i,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.Oma)(b,a);0<=c?(g.bb(b,c),b=!0):b=!1;return b||g.db(this.i,a)};
g.h.Ac=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.i.length;for(b=0;b<c;++b)a.push(this.i[b]);return a};
var oqa={SN:"atp",iQ:"ska",XP:"que",xP:"mus",hQ:"sus",OO:"dsp",eQ:"seq"};b6.prototype.hg=function(){var a=new b6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.l=this.l;a.i=this.i;a.g=this.g};
var v6,o6="",wqa=x6("loadCastFramework")||x6("loadCastApplicationFramework"),$qa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.Sa(D6,g.A);g.h=D6.prototype;g.h.tD=function(a){this.o=arguments;this.g=!1;this.Aa?this.l=(0,g.D)()+this.Yc:this.Aa=g.Gg(this.u,this.Yc)};
g.h.stop=function(){this.Aa&&(g.u.clearTimeout(this.Aa),this.Aa=null);this.l=null;this.g=!1;this.o=[]};
g.h.pause=function(){++this.i};
g.h.resume=function(){this.i&&(--this.i,!this.i&&this.g&&(this.g=!1,this.A.apply(null,this.o)))};
g.h.U=function(){this.stop();D6.bb.U.call(this)};
g.h.uD=function(){this.l?(this.Aa=g.Gg(this.u,this.l-(0,g.D)()),this.l=null):(this.Aa=null,this.i?this.g=!0:(this.g=!1,this.A.apply(null,this.o)))};E6.prototype.stringify=function(a){return g.u.JSON.stringify(a,void 0)};
E6.prototype.parse=function(a){return g.u.JSON.parse(a,void 0)};g.h=F6.prototype;g.h.Zg=null;g.h.De=!1;g.h.Yi=null;g.h.Et=null;g.h.Ii=null;g.h.Yh=null;g.h.Yf=null;g.h.Eg=null;g.h.sh=null;g.h.uc=null;g.h.pl=0;g.h.He=null;g.h.Fo=null;g.h.qg=null;g.h.Wj=-1;g.h.mA=!0;g.h.Og=!1;g.h.xq=0;g.h.Yn=null;var M6={},K6={};g.h=F6.prototype;g.h.setTimeout=function(a){this.o=a};
g.h.kM=function(a){a=a.target;var b=this.Yn;b&&3==S5(a)?b.Sj():this.sB(a)};
g.h.sB=function(a){try{if(a==this.uc)a:{var b=S5(this.uc),c=this.uc.u,d=this.uc.getStatus();if(g.Ld&&!g.od(10)||g.Nd&&!g.nd("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Ch&&!V5(this.uc))break a;this.Og||4!=b||7==c||(8==c||0>=d?this.g.Ae(3):this.g.Ae(2));W6(this);var e=this.uc.getStatus();this.Wj=e;var f=V5(this.uc);(this.De=200==e)?(4==b&&O6(this),this.u?(Q6(this,b,f),g.Ch&&this.De&&3==b&&(this.ca.da(this.i,"tick",this.eM),this.i.start())):N6(this,f),this.De&&!this.Og&&(4==b?this.g.Ln(this):(this.De=
!1,J6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.qg=3,L6(13)):(this.qg=0,L6(14)),O6(this),P6(this))}}catch(k){this.uc&&V5(this.uc)}finally{}};
g.h.eM=function(){var a=S5(this.uc),b=V5(this.uc);this.pl<b.length&&(W6(this),Q6(this,a,b),this.De&&4!=a&&J6(this))};
g.h.AL=function(a){V6((0,g.x)(this.zL,this,a),0)};
g.h.zL=function(a){this.Og||(W6(this),N6(this,a),J6(this))};
g.h.sz=function(a){V6((0,g.x)(this.yL,this,a),0)};
g.h.yL=function(a){this.Og||(O6(this),this.De=a,this.g.Ln(this),this.g.Ae(4))};
g.h.cancel=function(){this.Og=!0;O6(this)};
g.h.KL=function(){this.Yi=null;var a=(0,g.D)();0<=a-this.Et?(2!=this.Yh&&this.g.Ae(3),O6(this),this.qg=2,L6(18),P6(this)):U6(this,this.Et-a)};
g.h.getLastError=function(){return this.qg};g.h=$6.prototype;g.h.uq=null;g.h.Gd=null;g.h.Zn=!1;g.h.uw=null;g.h.nm=null;g.h.fr=null;g.h.wq=null;g.h.he=null;g.h.Af=-1;g.h.Vj=null;g.h.nj=null;g.h.connect=function(a){this.wq=a;a=a7(this.g,null,this.wq);L6(3);this.uw=(0,g.D)();var b=this.g.D;null!=b?(this.Vj=b[0],(this.nj=b[1])?(this.he=1,b7(this)):(this.he=2,d7(this))):(L5(a,"MODE","init"),this.Gd=new F6(this,void 0,void 0,void 0),this.Gd.Zg=this.uq,I6(this.Gd,a,!1,null,!0),this.he=0)};
g.h.BC=function(a){if(a)this.he=2,d7(this);else{L6(4);var b=this.g;b.Me=b.gg.Af;x7(b,9)}a&&this.Ae(2)};
g.h.Qp=function(a){return this.g.Qp(a)};
g.h.abort=function(){this.Gd&&(this.Gd.cancel(),this.Gd=null);this.Af=-1};
g.h.tw=function(){return!1};
g.h.mz=function(a,b){this.Af=a.Wj;if(0==this.he)if(b){try{var c=this.i.parse(b)}catch(d){c=this.g;c.Me=this.Af;x7(c,2);return}this.Vj=c[0];this.nj=c[1]}else c=this.g,c.Me=this.Af,x7(c,2);else if(2==this.he)if(this.Zn)L6(7),this.fr=(0,g.D)();else if("11111"==b){if(L6(6),this.Zn=!0,this.nm=(0,g.D)(),c=this.nm-this.uw,!g.Ld||g.od(10)||500>c)this.Af=200,this.Gd.cancel(),L6(12),c7(this.g,this,!0)}else L6(8),this.nm=this.fr=(0,g.D)(),this.Zn=!1};
g.h.Ln=function(){this.Af=this.Gd.Wj;if(this.Gd.De)0==this.he?this.nj?(this.he=1,b7(this)):(this.he=2,d7(this)):2==this.he&&((!g.Ld||g.od(10)?!this.Zn:200>this.fr-this.nm)?(L6(11),c7(this.g,this,!1)):(L6(12),c7(this.g,this,!0)));else{0==this.he?L6(9):2==this.he&&L6(10);var a=this.g;this.Gd.getLastError();a.Me=this.Af;x7(a,2)}};
g.h.Xk=function(){return this.g.Xk()};
g.h.isActive=function(){return this.g.isActive()};
g.h.Ae=function(a){this.g.Ae(a)};g.h=e7.prototype;g.h.Dj=null;g.h.Dd=null;g.h.Vb=null;g.h.tq=null;g.h.pm=null;g.h.Ku=null;g.h.Dm=null;g.h.Bk=0;g.h.QH=0;g.h.Vc=null;g.h.ng=null;g.h.qf=null;g.h.Tg=null;g.h.gg=null;g.h.Do=null;g.h.li=-1;g.h.fx=-1;g.h.Me=-1;g.h.Rh=0;g.h.Kh=0;g.h.Pg=8;var y7=new g.Sf;g.Sa(f7,g.sf);g.Sa(g7,g.sf);g.Sa(h7,g.sf);g.h=e7.prototype;g.h.connect=function(a,b,c,d,e){L6(0);this.tq=b;this.Dj=c||{};d&&g.Ca(e)&&(this.Dj.OSID=d,this.Dj.OAID=e);this.A?(V6((0,g.x)(this.dv,this,a),100),n7(this)):this.dv(a)};
g.h.dv=function(a){this.gg=new $6(this);this.gg.uq=null;this.gg.i=this.u;this.gg.connect(a)};
g.h.tw=function(){return 0==this.g};
g.h.rz=function(a){this.ng=null;s7(this,a)};
g.h.qz=function(){this.qf=null;this.Vb=new F6(this,this.l,"rpc",this.C);this.Vb.Zg=null;this.Vb.xq=0;var a=this.Ku.clone();g.kn(a,"RID","rpc");g.kn(a,"SID",this.l);g.kn(a,"CI",this.Do?"0":"1");g.kn(a,"AID",this.li);j7(this,a);if(!g.Ld||g.od(10))g.kn(a,"TYPE","xmlhttp"),I6(this.Vb,a,!0,this.Dm,!1);else{g.kn(a,"TYPE","html");var b=this.Vb,c=!!this.Dm;b.Yh=3;b.Yf=K5(a.clone());T6(b,c)}};
g.h.mz=function(a,b){if(0!=this.g&&(this.Vb==a||this.Dd==a))if(this.Me=a.Wj,this.Dd==a&&3==this.g)if(7<this.Pg){try{var c=this.u.parse(b)}catch(f){c=null}if(g.Ka(c)&&3==c.length)if(0==c[0])a:{if(!this.qf){if(this.Vb)if(this.Vb.Ii+3E3<this.Dd.Ii)o7(this),this.Vb.cancel(),this.Vb=null;else break a;v7(this);L6(19)}}else this.fx=c[1],0<this.fx-this.li&&37500>c[2]&&this.Do&&0==this.Kh&&!this.Tg&&(this.Tg=V6((0,g.x)(this.sI,this),6E3));else x7(this,11)}else b!=Lra.pO.g&&x7(this,11);else if(this.Vb==a&&
o7(this),!g.wb(b)){c=this.u.parse(b);g.Ka(c);for(var d=0;d<c.length;d++){var e=c[d];this.li=e[0];e=e[1];2==this.g?"c"==e[0]?(this.l=e[1],this.Dm=e[2],e=e[3],null!=e?this.Pg=e:this.Pg=6,this.g=3,this.Vc&&this.Vc.Xu(),this.Ku=a7(this,this.Xk()?this.Dm:null,this.tq),t7(this)):"stop"==e[0]&&x7(this,7):3==this.g&&("stop"==e[0]?x7(this,7):"noop"!=e[0]&&this.Vc&&this.Vc.Wu(e),this.Kh=0)}}};
g.h.sI=function(){null!=this.Tg&&(this.Tg=null,this.Vb.cancel(),this.Vb=null,v7(this),L6(20))};
g.h.Ln=function(a){if(this.Vb==a){o7(this);this.Vb=null;var b=2}else if(this.Dd==a)this.Dd=null,b=1;else return;this.Me=a.Wj;if(0!=this.g)if(a.De)1==b?(b=(0,g.D)()-a.Ii,y7.dispatchEvent(new g7(y7,a.sh?a.sh.length:0,b,this.Rh)),m7(this),this.o.length=0):t7(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Me)){if(d=1==b)this.Dd||this.ng||1==this.g||2<=this.Rh?d=!1:(this.ng=V6((0,g.x)(this.rz,this,a),u7(this,this.Rh)),this.Rh++,d=!0);d=!(d||2==b&&v7(this))}if(d)switch(c){case 1:x7(this,
5);break;case 4:x7(this,10);break;case 3:x7(this,6);break;case 7:x7(this,12);break;default:x7(this,2)}}};
g.h.TC=function(a){if(!g.$a(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.QM=function(a){a?L6(2):(L6(1),w7(this,8))};
g.h.Qp=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new U5;a.T=!1;return a};
g.h.isActive=function(){return!!this.Vc&&this.Vc.isActive(this)};
g.h.Ae=function(a){y7.dispatchEvent(new h7(y7,a))};
g.h.Xk=function(){return!(!g.Ld||g.od(10))};
g.h=z7.prototype;g.h.Xu=function(){};
g.h.Wu=function(){};
g.h.Vu=function(){};
g.h.Ep=function(){};
g.h.Tv=function(){return{}};
g.h.isActive=function(){return!0};g.Sa(A7,g.A);g.h=A7.prototype;g.h.sL=function(){this.Yc=Math.min(3E5,2*this.Yc);this.l();this.i&&this.start()};
g.h.start=function(){var a=this.Yc+15E3*Math.random();g.vo(this.g,a);this.i=(0,g.D)()+a};
g.h.stop=function(){this.g.stop();this.i=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Yc=5E3};g.Sa(B7,z7);g.h=B7.prototype;g.h.subscribe=function(a,b,c){return this.l.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.l.unsubscribe(a,b,c)};
g.h.Kf=function(a){return this.l.ah(a)};
g.h.N=function(a,b){return this.l.N.apply(this.l,arguments)};
g.h.dispose=function(){this.ib||(this.ib=!0,g.qf(this.l),C7(this),g.qf(this.i),this.i=null)};
g.h.fa=function(){return this.ib};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.F="";this.i.stop();this.u=a||null;this.o=b||0;a=this.H+"/test";b=this.H+"/bind";var d=new e7(c?c.firstTestResults:null,c?c.secondTestResults:null,this.I),e=this.g;e&&(e.Vc=null);d.Vc=this;this.g=d;e?this.g.connect(a,b,this.A,e.l,e.li):c?this.g.connect(a,b,this.A,c.sessionId,c.arrayId):this.g.connect(a,b,this.A)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.ec(c,b);this.i.isActive()||2==(this.g?this.g.g:0)?this.C.push(c):D7(this)&&p7(this.g,c)};
g.h.Xu=function(){this.i.reset();this.u=null;this.o=0;if(this.C.length){var a=this.C;this.C=[];for(var b=0,c=a.length;b<c;++b)p7(this.g,a[b])}this.N("handlerOpened")};
g.h.Vu=function(a){var b=2==a&&401==this.g.Me;4==a||b||this.i.start();this.N("handlerError",a)};
g.h.Ep=function(a){if(!this.i.isActive())this.N("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.C.push(d)}};
g.h.Tv=function(){var a={v:2};this.F&&(a.gsessionid=this.F);0!=this.o&&(a.ui=""+this.o);0!=this.D&&(a.ui=""+this.D);this.u&&g.ec(a,this.u);return a};
g.h.Wu=function(a){"S"==a[0]?this.F=a[1]:"gracefulReconnect"==a[0]?(this.i.start(),l7(this.g)):this.N("handlerMessage",new Aqa(a[0],a[1]))};
g.h.uM=function(){this.i.isActive();var a=this.g,b=0;a.Vb&&b++;a.Dd&&b++;0==b&&this.connect(this.u,this.o)};E7.prototype.o=function(a,b,c,d){b?a(d):a({text:c.responseText})};
E7.prototype.l=function(a,b){a(Error("Request error: "+b.status))};
E7.prototype.u=function(a){a(Error("request timed out"))};var Gqa=(0,g.D)(),J7=null,N7=Array(50),M7=-1,O7=!1;g.Sa(P7,g.N);P7.prototype.Qd=function(){return this.g};
P7.prototype.contains=function(a){return!!j6(this.g,a)};
P7.prototype.get=function(a){return a?k6(this.g,a):null};
P7.prototype.info=function(a){L7(this.C,a)};g.t(R7,g.N);g.h=R7.prototype;g.h.start=function(){!this.g&&isNaN(this.Aa)&&this.vB()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);isNaN(this.Aa)||(g.Zp(this.Aa),this.Aa=NaN)};
g.h.U=function(){this.stop();g.N.prototype.U.call(this)};
g.h.vB=function(){this.Aa=NaN;this.g=g.Uq(F7(this.A,"/pairing/get_screen"),{method:"POST",vb:{pairing_code:this.u},timeout:5E3,onSuccess:(0,g.x)(this.rN,this),onError:(0,g.x)(this.qN,this),ne:(0,g.x)(this.sN,this)})};
g.h.rN=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.l;c.name=this.o;this.N("pairingComplete",new c6(c))};
g.h.qN=function(a){this.g=null;a.status&&404==a.status?this.i>=Mra.length?this.N("pairingFailed",Error("DIAL polling timed out")):(a=Mra[this.i],this.Aa=g.Xp((0,g.x)(this.vB,this),a),this.i++):this.N("pairingFailed",Error("Server error "+a.status))};
g.h.sN=function(){this.g=null;this.N("pairingFailed",Error("Server not responding"))};
var Mra=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Sa(T7,P7);g.h=T7.prototype;g.h.start=function(){S7(this)&&this.N("screenChange");!g.zt("yt-remote-lounge-token-expiration")&&U7(this);g.Zp(this.i);this.i=g.Xp((0,g.x)(this.start,this),1E4)};
g.h.add=function(a,b){S7(this);Q7(this,a);V7(this,!1);this.N("screenChange");b(a);a.token||U7(this)};
g.h.remove=function(a,b){var c=S7(this);Iqa(this,a)&&(V7(this,!1),c=!0);b(a);c&&this.N("screenChange")};
g.h.zo=function(a,b,c,d){var e=S7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,V7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.N("screenChange")};
g.h.U=function(){g.Zp(this.i);T7.bb.U.call(this)};
g.h.ED=function(a){S7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}V7(this,!b);b&&L7(this.C,"Missed "+b+" lounge tokens.")};
g.h.DD=function(a){L7(this.C,"Requesting lounge tokens failed: "+a)};g.t(X7,g.N);g.h=X7.prototype;g.h.start=function(){var a=parseInt(g.zt("yt-remote-fast-check-period")||"0",10);(this.o=(0,g.D)()-144E5<a?0:a)?$7(this):(this.o=(0,g.D)()+3E5,g.xt("yt-remote-fast-check-period",this.o),this.Is())};
g.h.isEmpty=function(){return g.Xb(this.g)};
g.h.update=function(){W7("Updating availability on schedule.");var a=this.A(),b=g.Lb(this.g,function(c,d){return c&&!!k6(a,d)},this);
Z7(this,b)};
g.h.U=function(){g.Zp(this.l);this.l=NaN;this.i&&(this.i.abort(),this.i=null);g.N.prototype.U.call(this)};
g.h.Is=function(){g.Zp(this.l);this.l=NaN;this.i&&this.i.abort();var a=Kqa(this);if(X5(a)){var b=F7(this.u,"/pairing/get_screen_availability");this.i=G7(this.u,b,{lounge_token:g.Rb(a).join(",")},(0,g.x)(this.WK,this,a),(0,g.x)(this.VK,this))}else Z7(this,{}),$7(this)};
g.h.WK=function(a,b){this.i=null;var c=g.Rb(Kqa(this));if(g.rb(c,g.Rb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;Z7(this,d);$7(this)}else this.Hb("Changing Screen set during request."),this.Is()};
g.h.VK=function(a){this.Hb("Screen availability failed: "+a);this.i=null;$7(this)};
g.h.Hb=function(a){L7("OnlineScreenService",a)};g.Sa(a8,P7);g.h=a8.prototype;g.h.start=function(){this.l.start();this.i.start();this.g.length&&(this.N("screenChange"),this.i.isEmpty()||this.N("onlineScreenChange"))};
g.h.add=function(a,b,c){this.l.add(a,b,c)};
g.h.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.h.zo=function(a,b,c,d){this.l.contains(a)?this.l.zo(a,b,c,d):(a="Updating name of unknown screen: "+a.name,L7(this.C,a),d(Error(a)))};
g.h.Qd=function(a){return a?this.g:g.fb(this.g,(0,g.Xd)(this.o,function(b){return!this.contains(b)},this))};
g.h.wB=function(){return(0,g.Xd)(this.Qd(!0),function(a){return!!this.i.g[a.id]},this)};
g.h.xB=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new R7(this.A,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(k){g.qf(f);d(b8(this,k))},this));
f.subscribe("pairingFailed",function(k){g.qf(f);e(k)});
f.start();return(0,g.x)(f.stop,f)};
g.h.uN=function(a,b,c,d){g.Uq(F7(this.A,"/pairing/get_screen"),{method:"POST",vb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var k=new c6(f.screen||{});if(!k.name||Oqa(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);Oqa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(b8(this,k))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
ne:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.h.U=function(){g.qf(this.l);g.qf(this.i);a8.bb.U.call(this)};
g.h.MD=function(){Pqa(this);this.N("screenChange");this.i.update()};
a8.prototype.dispose=a8.prototype.dispose;g.Sa(d8,g.N);g.h=d8.prototype;g.h.Nn=function(a){this.l=a;this.N("sessionScreen",this.l)};
g.h.Td=function(a){this.fa()||(a&&e8(this,""+a),this.l=null,this.N("sessionScreen",null))};
g.h.info=function(a){L7(this.P,a)};
g.h.zB=function(){return null};
g.h.Rs=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){e8(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.U=function(){this.Rs("");d8.bb.U.call(this)};g.Sa(f8,d8);g.h=f8.prototype;g.h.Qs=function(a){if(this.g){if(this.g==a)return;e8(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.A);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u)}this.g=a;this.g.addUpdateListener(this.A);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.u);Rqa(this)};
g.h.ni=function(a){this.info("launchWithParams no-op for Cast: "+g.Kg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.x)(function(){this.Td()},this),(0,g.x)(function(){this.Td(Error("Failed to stop receiver app."))},this)):this.Td(Error("Stopping cast device witout session."))};
g.h.Rs=g.Ha;g.h.U=function(){this.info("disposeInternal");g.Zp(this.o);this.o=0;this.g&&(this.g.removeUpdateListener(this.A),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u));this.g=null;f8.bb.U.call(this)};
g.h.VL=function(a,b){if(!this.fa())if(b){var c=Z5(b);if(g.Na(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Kg(c));switch(d){case "mdxSessionStatus":Qqa(this,c.screenId);break;default:e8(this,"Unknown youtube message: "+d)}}else e8(this,"Unable to parse message.")}else e8(this,"No data in message.")};
g.h.kw=function(a,b,c,d){Nqa(this.F,this.i.label,a,this.i.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(e8(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Xp((0,g.x)(this.kw,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.zB=function(){return this.g};
g.h.vN=function(a){this.fa()||a||(e8(this,"Cast session died."),this.Td())};g.Sa(g8,d8);g.h=g8.prototype;g.h.Qs=function(a){this.o=a;this.o.addUpdateListener(this.I)};
g.h.ni=function(a){this.u=a;this.C()};
g.h.stop=function(){this.g();this.g=g.Ha;g.Zp(this.A);this.o?this.o.stop((0,g.x)(this.Td,this,null),(0,g.x)(this.Td,this,"Failed to stop DIAL device.")):this.Td()};
g.h.U=function(){this.g();this.g=g.Ha;g.Zp(this.A);this.o&&this.o.removeUpdateListener(this.I);this.o=null;g8.bb.U.call(this)};
g.h.yN=function(a){this.fa()||a||(e8(this,"DIAL session died."),this.g(),this.g=g.Ha,this.Td())};
g.h.Jq=function(a){this.H=i6();if(this.u){var b=new chrome.cast.DialLaunchResponse(!0,Tqa(this));a(b);Sqa(this)}else this.C=(0,g.x)(function(){g.Zp(this.A);this.C=g.Ha;this.A=NaN;var c=new chrome.cast.DialLaunchResponse(!0,Tqa(this));a(c);Sqa(this)},this),this.A=g.Xp((0,g.x)(function(){this.C()},this),100)};
g.h.hE=function(a,b,c){Nqa(this.F,this.D.receiver.label,a,this.i.friendlyName,(0,g.x)(function(d){d&&d.token?(this.Nn(d),b(new chrome.cast.DialLaunchResponse(!1))):this.Jq(b,c)},this),(0,g.x)(function(d){e8(this,"Failed to get DIAL screen: "+d);
this.Jq(b,c)},this))};g.Sa(h8,d8);h8.prototype.stop=function(){this.Td()};
h8.prototype.Qs=g.Ha;h8.prototype.ni=function(){g.Zp(this.g);this.g=NaN;var a=k6(this.F.Qd(),this.i.label);a?this.Nn(a):this.Td(Error("No such screen"))};
h8.prototype.U=function(){g.Zp(this.g);this.g=NaN;h8.bb.U.call(this)};g.Sa(i8,g.N);g.h=i8.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.C);this.D||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.FK,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.oz,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.UI,this);chrome.cast.initialize(c,(0,g.x)(function(){this.fa()||
(chrome.cast.addReceiverActionListener(this.o),Dqa(),this.i.subscribe("onlineScreenChange",(0,g.x)(this.yB,this)),this.l=Vqa(this),chrome.cast.setCustomReceivers(this.l,g.Ha,(0,g.x)(function(k){this.Hb("Failed to set initial custom receivers: "+g.Kg(k))},this)),this.N("yt-remote-cast2-availability-change",k8(this)),b(!0))},this),(0,g.x)(function(k){this.Hb("Failed to initialize API: "+g.Kg(k));
b(!1)},this))};
g.h.DM=function(a,b){j8("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.l;if(!a||c&&c.id!=a)j8("Unsetting old screen status: "+this.g.i.friendlyName),l8(this,null)}if(a&&b){if(!this.g){c=k6(this.i.Qd(),a);if(!c){j8("setConnectedScreenStatus: Unknown screen.");return}var d=Uqa(this,c);d||(j8("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.l.push(d),chrome.cast.setCustomReceivers(this.l,
g.Ha,(0,g.x)(function(e){this.Hb("Failed to set initial custom receivers: "+g.Kg(e))},this)));
j8("setConnectedScreenStatus: new active receiver: "+d.friendlyName);l8(this,new h8(this.i,d),!0)}this.g.Rs(b)}else j8("setConnectedScreenStatus: no screen.")};
g.h.EM=function(a){this.fa()?this.Hb("Setting connection data on disposed cast v2"):this.g?this.g.ni(a):this.Hb("Setting connection data without a session")};
g.h.xN=function(){this.fa()?this.Hb("Stopping session on disposed cast v2"):this.g?(this.g.stop(),l8(this,null)):j8("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.oz,this),(0,g.x)(this.bL,this))};
g.h.U=function(){this.i.unsubscribe("onlineScreenChange",(0,g.x)(this.yB,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.o);g.db(g.w("yt.mdx.remote.debug.handlers_")||[],H7);g.qf(this.g);i8.bb.U.call(this)};
g.h.Hb=function(a){L7("Controller",a)};
g.h.pz=function(a,b){this.g==a&&(b||l8(this,null),this.N("yt-remote-cast2-session-change",b))};
g.h.BK=function(a,b){if(!this.fa())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),j8("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.i.label!=a.label)j8("onReceiverAction_: Stopping active receiver: "+this.g.i.friendlyName),this.g.stop();else{j8("onReceiverAction_: Casting to active receiver.");this.g.l&&this.N("yt-remote-cast2-session-change",this.g.l);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:l8(this,
new h8(this.i,a));break;case chrome.cast.ReceiverType.DIAL:l8(this,new g8(this.i,a,this.A));break;case chrome.cast.ReceiverType.CAST:l8(this,new f8(this.i,a));break;default:this.Hb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.g&&this.g.i.label==a.label?this.g.stop():this.Hb("Stopping receiver w/o session: "+a.friendlyName)}else this.Hb("onReceiverAction_ called without receiver.")};
g.h.UI=function(a){if(this.fa())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Hb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.i:null;if(!c||c.label!=b.label)return this.Hb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.g.l)return j8("Reselecting dial screen."),
this.N("yt-remote-cast2-session-change",this.g.l),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Hb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);l8(this,new g8(this.i,b,this.A))}b=this.g;b.D=a;return b.D.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.hE,b,(b.D.extraData||{}).screenId||null)):new Promise((0,g.x)(b.Jq,b))};
g.h.oz=function(a){if(!this.fa()){j8("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==chrome.cast.ReceiverType.CAST)j8("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),l8(this,new f8(this.i,b),!0);else{this.Hb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.i,d=k6(this.i.Qd(),c.label);d&&d6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(j8("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.qf(this.g),this.g=new f8(this.i,b),this.g.subscribe("sessionScreen",(0,g.x)(this.pz,this,this.g)),this.g.ni(null));this.g.Qs(a)}}};
g.h.wN=function(){return this.g?this.g.zB():null};
g.h.bL=function(a){this.fa()||(this.Hb("Failed to estabilish a session: "+g.Kg(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&l8(this,null))};
g.h.FK=function(a){j8("Receiver availability updated: "+a);if(!this.fa()){var b=k8(this);this.u=a==chrome.cast.ReceiverAvailability.AVAILABLE;k8(this)!=b&&this.N("yt-remote-cast2-availability-change",k8(this))}};
g.h.yB=function(){this.fa()||(this.l=Vqa(this),j8("Updating custom receivers: "+g.Kg(this.l)),chrome.cast.setCustomReceivers(this.l,g.Ha,(0,g.x)(function(){this.Hb("Failed to set custom receivers.")},this)),this.N("yt-remote-cast2-availability-change",k8(this)))};
i8.prototype.setLaunchParams=i8.prototype.EM;i8.prototype.setConnectedScreenStatus=i8.prototype.DM;i8.prototype.stopSession=i8.prototype.xN;i8.prototype.getCastSession=i8.prototype.wN;i8.prototype.requestSession=i8.prototype.requestSession;i8.prototype.init=i8.prototype.init;i8.prototype.dispose=i8.prototype.dispose;var r8=[];w8.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";x8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.g=a.trackData,this.Ne=a.hasPrevious,this.hasNext=a.hasNext,this.C=a.playerTime,this.A=a.playerTimeAt,this.o=a.seekableStart,this.i=a.seekableEnd,this.D=a.duration,this.F=a.loadedTime,this.l=a.liveIngestionTime,this.u=
!isNaN(this.l))};
w8.prototype.isAdPlaying=function(){return 1081==this.playerState};
w8.prototype.getDuration=function(){return this.u?this.D+y8(this):this.D};
w8.prototype.clone=function(){return new w8(C8(this))};g.t(E8,g.N);g.h=E8.prototype;g.h.play=function(){1==this.g?(this.i?this.i.play(null,g.Ha,K8(this,"play")):J8(this,"play"),I8(this,1,A8(F8(this))),this.N("remotePlayerChange")):G8(this,this.play)};
g.h.pause=function(){1==this.g?(this.i?this.i.pause(null,g.Ha,K8(this,"pause")):J8(this,"pause"),I8(this,2,A8(F8(this))),this.N("remotePlayerChange")):G8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.g){if(this.i){var b=F8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ha,K8(this,"seekTo",{newTime:a}))}else J8(this,"seekTo",{newTime:a});I8(this,3,a);this.N("remotePlayerChange")}else G8(this,g.Qa(this.seekTo,a))};
g.h.stop=function(){if(1==this.g){this.i?this.i.stop(null,g.Ha,K8(this,"stopVideo")):J8(this,"stopVideo");var a=F8(this);a.index=-1;a.videoId="";x8(a);H8(this,a);this.N("remotePlayerChange")}else G8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=F8(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.x)(function(){L7("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.Hb("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.x)(function(){L7("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.Hb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);J8(this,"setVolume",e)}c.muted=b;c.volume=a;H8(this,c)}else G8(this,g.Qa(this.setVolume,a,b))};
g.h.zA=function(a,b){if(1==this.g){var c=F8(this),d={videoId:a};b&&(c.g={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Kg(b.style),g.ec(d,c.g));J8(this,"setSubtitlesTrack",d);H8(this,c)}else G8(this,g.Qa(this.zA,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.g){var c=b.getLanguageInfo().getId();J8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=F8(this);d.audioTrackId=c;H8(this,d)}else G8(this,g.Qa(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=F8(this);c=c||0;var m={videoId:a,currentIndex:c};B8(l,a,c);g.Ca(b)&&(z8(l,b),m.currentTime=b);g.Ca(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Kg(k));J8(this,"setPlaylist",m);d||H8(this,l)};
g.h.Tn=function(a,b){if(1==this.g){if(a&&b){var c=F8(this);B8(c,a,b);H8(this,c)}J8(this,"previous")}else G8(this,g.Qa(this.Tn,a,b))};
g.h.nextVideo=function(a,b){if(1==this.g){if(a&&b){var c=F8(this);B8(c,a,b);H8(this,c)}J8(this,"next")}else G8(this,g.Qa(this.nextVideo,a,b))};
g.h.Av=function(){1==this.g?J8(this,"dismissAutoplay"):G8(this,this.Av)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.N("proxyStateChange",a,this.g)}g.N.prototype.dispose.call(this)};
g.h.U=function(){hra(this);this.o=null;this.u.clear();D8(this,null);g.N.prototype.U.call(this)};
g.h.Ht=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.N("proxyStateChange",b,a);if(1==a)for(;!this.u.isEmpty();)b=a=this.u,0==b.g.length&&(b.g=b.i,b.g.reverse(),b.i=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.yK=function(a,b){this.N(a,b)};
g.h.yI=function(a){if(!a)this.Ek(null),D8(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=F8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)L7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,H8(this,b)}};
g.h.Ek=function(a){L7("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.D);if(this.i=a)this.i.addUpdateListener(this.D),ira(this),this.N("remotePlayerChange")};
g.h.xI=function(a){a?(ira(this),this.N("remotePlayerChange")):this.Ek(null)};
g.h.mt=function(){J8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.MI=function(){var a=era();a&&D8(this,a)};
g.h.Hb=function(a){L7("CP",a)};g.t(L8,g.N);g.h=L8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.Ca(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.Ca(k)&&(l.currentIndex=k);c&&(this.Oa.listId=c);this.Oa.videoId=d;this.Oa.index=k||0;this.Oa.state=3;z8(this.Oa,m);this.o="UNSUPPORTED";M8("Connecting with setPlaylist and params: "+g.Kg(l));this.g.connect({method:"setPlaylist",
params:g.Kg(l)},a,r6())}else M8("Connecting without params"),this.g.connect({},a,r6());kra(this)};
g.h.dispose=function(){this.fa()||(this.N("beforeDispose"),N8(this,3));g.N.prototype.dispose.call(this)};
g.h.U=function(){O8(this);Q8(this);P8(this);g.Zp(this.C);this.C=NaN;g.Zp(this.D);this.D=NaN;this.l=null;g.cs(this.P);this.P.length=0;this.g.dispose();g.N.prototype.U.call(this);this.o=this.A=this.i=this.Oa=this.g=null};
g.h.xD=function(){this.Oh(2)};
g.h.CI=function(){M8("Channel opened");this.I&&(this.I=!1,P8(this),this.H=g.Xp((0,g.x)(function(){M8("Timing out waiting for a screen.");this.Oh(1)},this),15E3));
uqa(Bqa(this.g),this.M)};
g.h.zI=function(){M8("Channel closed");isNaN(this.u)?u6(!0):u6();this.dispose()};
g.h.AI=function(a){u6();isNaN(this.Lj())?(M8("Channel error: "+a+" without reconnection"),this.dispose()):(this.I=!0,M8("Channel error: "+a+" with reconnection in "+this.Lj()+" ms"),N8(this,2))};
g.h.BI=function(a){a.params?M8("Received: action="+a.action+", params="+g.Kg(a.params)):M8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=Z5(a.params.devices);this.i=(0,g.ge)(a,function(c){return new b6(c)});
a=!!g.Xa(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
nra(this,a);break;case "loungeScreenDisconnected":g.eb(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
nra(this,!1);break;case "remoteConnected":var b=new b6(Z5(a.params.device));g.Xa(this.i,function(c){return b?c.id==b.id:!1})||jqa(this.i,b);
break;case "remoteDisconnected":b=new b6(Z5(a.params.device));g.eb(this.i,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":pra(this,a);break;case "nowPlaying":rra(this,a);break;case "onStateChange":qra(this,a);break;case "onAdStateChange":sra(this,a);break;case "onVolumeChanged":tra(this,a);break;case "onSubtitlesTrackChanged":ora(this,a);break;case "nowAutoplaying":ura(this,a);break;case "autoplayDismissed":this.N("autoplayDismissed");break;case "autoplayUpNext":this.A=a.params.videoId||null;this.N("autoplayUpNext",this.A);break;case "onAutoplayModeChanged":this.o=
a.params.autoplayMode;this.N("autoplayModeChange",this.o);"DISABLED"==this.o&&this.N("autoplayDismissed");break;case "onHasPreviousNextChanged":vra(this,a);break;case "requestAssistedSignIn":this.N("assistedSignInRequested",a.params.authCode);break;default:M8("Unrecognized action: "+a.action)}};
g.h.rM=function(){if(this.l){var a=this.l;this.l=null;this.Oa.videoId!=a&&R8(this,"getNowPlaying")}};
g.h.nD=function(){var a=3;this.fa()||(a=0,isNaN(this.Lj())?D7(this.g)&&isNaN(this.u)&&(a=1):a=2);return a};
g.h.Oh=function(a){M8("Disconnecting with "+a);O8(this);this.N("beforeDisconnect",a);1==a&&u6();C7(this.g,a);this.dispose()};
g.h.mD=function(){var a=this.Oa;this.l&&(a=this.Oa.clone(),B8(a,this.l,a.index));return C8(a)};
g.h.FM=function(a){var b=new w8(a);b.videoId&&b.videoId!=this.Oa.videoId&&(this.l=b.videoId,g.Zp(this.C),this.C=g.Xp((0,g.x)(this.rM,this),5E3));var c=[];this.Oa.listId==b.listId&&this.Oa.videoId==b.videoId&&this.Oa.index==b.index||c.push("remoteQueueChange");this.Oa.playerState==b.playerState&&this.Oa.volume==b.volume&&this.Oa.muted==b.muted&&A8(this.Oa)==A8(b)&&g.Kg(this.Oa.g)==g.Kg(b.g)||c.push("remotePlayerChange");this.Oa.reset(a);(0,g.y)(c,function(d){this.N(d)},this)};
g.h.iw=function(){var a=this.g.A.id,b=g.Xa(this.i,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.Lj=function(){var a=this.g;return a.i.isActive()?a.i.i-(0,g.D)():NaN};
g.h.fD=function(){return this.o||"UNSUPPORTED"};
g.h.gD=function(){return this.A||""};
g.h.pN=function(){if(!isNaN(this.Lj())){var a=this.g.i;g.wo(a.g);a.start()}};
g.h.yM=function(a,b){R8(this,a,b);mra(this)};
L8.prototype.subscribe=L8.prototype.subscribe;L8.prototype.unsubscribeByKey=L8.prototype.Kf;L8.prototype.getProxyState=L8.prototype.nD;L8.prototype.disconnect=L8.prototype.Oh;L8.prototype.getPlayerContextData=L8.prototype.mD;L8.prototype.setPlayerContextData=L8.prototype.FM;L8.prototype.getOtherConnectedRemoteId=L8.prototype.iw;L8.prototype.getReconnectTimeout=L8.prototype.Lj;L8.prototype.getAutoplayMode=L8.prototype.fD;L8.prototype.getAutoplayVideoId=L8.prototype.gD;L8.prototype.reconnect=L8.prototype.pN;
L8.prototype.sendMessage=L8.prototype.yM;g.t(S8,P7);g.h=S8.prototype;g.h.Qd=function(a){return this.Xc.$_gs(a)};
g.h.contains=function(a){return!!this.Xc.$_c(a)};
g.h.get=function(a){return this.Xc.$_g(a)};
g.h.start=function(){this.Xc.$_st()};
g.h.add=function(a,b,c){this.Xc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Xc.$_r(a,b,c)};
g.h.zo=function(a,b,c,d){this.Xc.$_un(a,b,c,d)};
g.h.U=function(){for(var a=0,b=this.i.length;a<b;++a)this.Xc.$_ubk(this.i[a]);this.i.length=0;this.Xc=null;P7.prototype.U.call(this)};
g.h.tN=function(){this.N("screenChange")};
g.h.dK=function(){this.N("onlineScreenChange")};
a8.prototype.$_st=a8.prototype.start;a8.prototype.$_gspc=a8.prototype.uN;a8.prototype.$_gsppc=a8.prototype.xB;a8.prototype.$_c=a8.prototype.contains;a8.prototype.$_g=a8.prototype.get;a8.prototype.$_a=a8.prototype.add;a8.prototype.$_un=a8.prototype.zo;a8.prototype.$_r=a8.prototype.remove;a8.prototype.$_gs=a8.prototype.Qd;a8.prototype.$_gos=a8.prototype.wB;a8.prototype.$_s=a8.prototype.subscribe;a8.prototype.$_ubk=a8.prototype.Kf;var k9=null,j9=!1,T8=null,U8=null,i9=null,Y8=[];g.t(l9,g.A);g.h=l9.prototype;
g.h.U=function(){g.A.prototype.U.call(this);this.o.stop();this.A.stop();this.I.stop();this.M();this.g.unsubscribe("proxyStateChange",this.lz,this);this.g.unsubscribe("remotePlayerChange",this.Gk,this);this.g.unsubscribe("remoteQueueChange",this.On,this);this.g.unsubscribe("autoplayUpNext",this.Py,this);this.g.unsubscribe("previousNextChange",this.iz,this);this.g.unsubscribe("nowAutoplaying",this.ez,this);this.g.unsubscribe("autoplayDismissed",this.Oy,this);this.g=this.u=null};
g.h.Lx=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(o9(this)){if(!F8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==F8(this.g).playerState?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.H.Sj(c[0],c[1]);break;case "control_subtitles_set_track":p9(this,c[0]);break;case "control_set_audio_track":c=c[0],o9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.i.getCurrentTime();q9(this,0==c?void 0:c);break;case "control_seek":q9(this,c[0]);break;case "control_subtitles_set_track":p9(this,c[0]);break;case "control_set_audio_track":c=c[0],o9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,c)}};
g.h.wI=function(a){this.I.tD(a)};
g.h.ZM=function(a){this.Lx("control_subtitles_set_track",g.Xb(a)?null:a)};
g.h.KA=function(){var a=this.i.getOption("captions","track");g.Xb(a)||p9(this,a)};
g.h.az=function(a){if(o9(this)){this.g.unsubscribe("remotePlayerChange",this.Gk,this);var b=Math.round(a.volume);a=!!a.muted;var c=F8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.P.start();this.g.subscribe("remotePlayerChange",this.Gk,this)}};
g.h.xJ=function(){g.Xb(this.C)||Hra(this,this.C);this.D=!1};
g.h.lz=function(a,b){this.A.stop();2==b&&this.JA()};
g.h.Gk=function(){if(o9(this)){this.o.stop();var a=F8(this.g);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.Um=1;break;case 1082:case 1083:this.u.Um=0;break;default:this.u.Um=-1}switch(a.playerState){case 1081:case 1:n9(this,new g.EC(8));this.IA();break;case 1085:case 3:n9(this,new g.EC(9));break;case 1083:case 0:n9(this,new g.EC(2));this.H.stop();m9(this,this.i.getVideoData().lengthSeconds);break;case 1084:n9(this,new g.EC(4));break;case 2:n9(this,new g.EC(4));m9(this,A8(a));
break;case -1:n9(this,new g.EC(64));break;case -1E3:n9(this,new g.EC(128,{errorCode:"mdx.remoteerror",errorMessage:"\u9019\u90e8\u5f71\u7247\u4e0d\u63d0\u4f9b\u9060\u7aef\u64ad\u653e\u3002\u3000"}))}a=F8(this.g).g;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.C=a,Hra(this,a));a=F8(this.g);-1==a.volume||Math.round(this.i.getVolume())==a.volume&&this.i.isMuted()==a.muted||this.P.isActive()||this.kB()}else Gra(this)};
g.h.iz=function(){this.i.N("mdxpreviousnextchange")};
g.h.On=function(){o9(this)||Gra(this)};
g.h.AC=function(){this.g.Av()};
g.h.Py=function(a){a&&(a=g.Uq("/watch_queue_ajax",{method:"GET",td:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.x)(this.DL,this)}))&&(this.M=(0,g.x)(a.abort,a))};
g.h.DL=function(a,b){var c=new g.oB(g.X(this.i),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.i.N("mdxautoplayupnext",c)};
g.h.ez=function(a){isNaN(a)||this.i.N("mdxnowautoplaying",a)};
g.h.Oy=function(){this.i.N("mdxautoplaycanceled")};
g.h.TF=function(a,b){-1==F8(this.g).playerState?q9(this,a):b&&this.g.seekTo(a)};
g.h.kB=function(){if(o9(this)){var a=F8(this.g);this.l.La(this.R);a.muted?this.i.mute():this.i.unMute();this.i.setVolume(a.volume);this.R=this.l.K(this.i,"onVolumeChange",this.az)}};
g.h.IA=function(){this.o.stop();if(!this.g.fa()){var a=F8(this.g);1==a.playerState&&n9(this,new g.EC(8));m9(this,A8(a));this.o.start()}};
g.h.JA=function(){this.A.stop();this.o.stop();var a=this.g.o.getReconnectTimeout();2==this.g.g&&!isNaN(a)&&this.A.start()};g.t(r9,g.W);r9.prototype.o=function(){a6("mdx-privacy-popup-cancel");this.l.hide()};
r9.prototype.A=function(){a6("mdx-privacy-popup-confirm");this.l.hide()};g.t(s9,g.W);s9.prototype.u=function(a){Jra(this,a.state)};g.t(t9,g.eU);t9.prototype.I=function(){var a=this.l.getOption("remote","receivers");a&&1<a.length&&!this.l.getOption("remote","quickCast")?(this.F=g.tb(a,this.A,this),g.fU(this,(0,g.ge)(a,this.A)),a=this.l.getOption("remote","currentReceiver"),this.ze(this.A(a)),this.enable(!0)):this.enable(!1)};
t9.prototype.A=function(a){return a.key};
t9.prototype.ye=function(a){return"cast-selector-receiver"==a?"\u6295\u653e\u2026":this.F[a].name};
t9.prototype.Kc=function(a){g.eU.prototype.Kc.call(this,a);this.l.setOption("remote","currentReceiver",this.F[a]);this.o.kb()};g.t(u9,g.$K);g.h=u9.prototype;
g.h.create=function(){Ara(g.Vy(g.X(this.player)));this.o.push(g.dq("yt-remote-before-disconnect",this.tI,this));this.o.push(g.dq("yt-remote-connection-change",this.GK,this));this.o.push(g.dq("yt-remote-receiver-availability-change",this.jz,this));this.o.push(g.dq("yt-remote-auto-connect",this.EK,this));this.o.push(g.dq("yt-remote-receiver-resumed",this.DK,this));this.o.push(g.dq("mdx-privacy-popup-confirm",this.hM,this));this.o.push(g.dq("mdx-privacy-popup-cancel",this.gM,this));this.jz()};
g.h.load=function(){this.player.cancelPlayback();g.$K.prototype.load.call(this);this.u=new l9(this,this.player,this.g);var a=(a=Fra())?a.currentTime:0;var b=h9()?new E8(c9(),void 0):null;0==a&&b&&(a=A8(F8(b)));0!=a&&this.Mc(a);Ira(this,this.pk,this.pk);g.eY(this.player.app,6)};
g.h.unload=function(){this.player.N("mdxautoplaycanceled");this.l=this.i;g.rf(this.u,this.g);this.g=this.u=null;g.$K.prototype.unload.call(this);g.eY(this.player.app,5);v9(this)};
g.h.U=function(){g.eq(this.o);g.$K.prototype.U.call(this)};
g.h.af=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.u.Lx.apply(this.u,[a].concat(g.ea(c)))};
g.h.getAdState=function(){return this.Um};
g.h.pD=function(){return this.loaded?this.u.suggestion:null};
g.h.Ne=function(){return this.g?F8(this.g).Ne:!1};
g.h.hasNext=function(){return this.g?F8(this.g).hasNext:!1};
g.h.Mc=function(a,b){this.I=a||0;this.player.N("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.I};
g.h.getProgressState=function(){var a=F8(this.g),b=this.player.getVideoData();return{allowSeeking:g.O(g.X(this.player).experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.fc():!a.isAdPlaying()&&this.player.fc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.l+y8(a):a.l,isAtLiveHead:1>=(a.u?a.i+y8(a):a.i)-this.getCurrentTime(),loaded:a.F,seekableEnd:a.u?a.i+y8(a):a.i,seekableStart:0<a.o?a.o+
y8(a):a.o}};
g.h.nextVideo=function(){this.g&&this.g.nextVideo()};
g.h.Tn=function(){this.g&&this.g.Tn()};
g.h.tI=function(a){1==a&&(this.F=this.g?F8(this.g):null)};
g.h.GK=function(){var a=h9()?new E8(c9(),void 0):null;if(a){var b=this.l;this.loaded&&this.unload();this.g=a;this.F=null;b.key!=this.i.key&&(this.l=b,this.load())}else g.qf(this.g),this.g=null,this.loaded&&(this.unload(),(a=this.F)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,A8(a)));this.player.N("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.jz=function(){this.C=[this.i].concat(Cra());var a=d9()||this.i;w9(this,a);this.player.la("onMdxReceiversChange")};
g.h.bM=function(a){!this.D&&g.RD(a,8)&&(this.player.pauseVideo(),v9(this))};
g.h.EK=function(){var a=d9();w9(this,a)};
g.h.DK=function(){this.l=d9()};
g.h.hM=function(){this.D=!0;v9(this);j9=!1;k9&&f9(k9,1);k9=null};
g.h.gM=function(){this.D=!1;v9(this);w9(this,this.i);this.l=this.i;j9=!1;k9=null;this.player.playVideo()};
g.h.yc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.C;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?u8():w9(this,b)),this.loaded?this.l:this.i;case "quickCast":return 2==this.C.length&&"cast-selector-receiver"==this.C[1].key?(b&&u8(),!0):!1}};
g.h.mt=function(){this.g.mt()};
g.h.Ob=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.uV.remote=u9;})(_yt_player);
